apiVersion: v1
kind: Secret
metadata:
    name: blueprint-auth-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:FdJSZ51n9GiFEFKU9p9AM0o/Yeg/6zgkNX3zicWYycS8TeFHYxZDZN/cOcayV4Pv5gcj4g90sNbEBXw/JdiBDIb9vg==,iv:D7GhlfEi0rLgFV6Cowa5VNUwiBPRZKF4ne+76GMCX3g=,tag:Rbhc408nrhavmIxyAMj0Ew==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:ISM51AzrxYpKJkqcxd09msVXsba2TEgv9Qv0q51o5OcjFr1ww+SQOypMTgsoZ9tjpuwpS7Pg4c43RDpj65VZbA==,iv:YZCcgi/j1NpA8worx1KT6o0aNga9EyCHrctwZLaVR64=,tag:qgnKAW7fv6JJmUI3vje6SA==,type:str]
    WEBHOOK_SECRET_TOKEN: ENC[AES256_GCM,data:WGfaoQF9jDEMRIq6RfOyaZ3QU12OI6a48mYS2vNVMtDZTPmbs7fDwgZsIAlIMyObf0SFUnRx8/TkP6liITQCMg==,iv:l6qttoN0Z3ZbB7tOC9ptseSNZlpq06AAcJW1pWsRQ9s=,tag:czcTWxpgsqD2Tggi5RPwRg==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:IAKgZiz1yrw=,iv:gPSY69URkYCJCTNKuIDX2+KNLvV5vMdpU/yX4g9aCF0=,tag:w3fe+kefkO4iNV1NqR/tZw==,type:str]
    SMTP_USER: ""
    SMTP_PASSWORD: ""
    INTERNAL_API_TOKEN: ENC[AES256_GCM,data:llkzyDqOPzlS9lUlF1HeN8i5k1fgNzUnAH0bdfuBmzlrllIho/qEo9NWsQ==,iv:tbHrPGGbeFV2X4JPYM3aMMH4FFXapKcVqaWsTx6rqLs=,tag:IjMgCPbAwxNYkEMNH/kwig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMFBqWXplbVU4cWRGdkRE
            WGFxZ1RVZUp6VkZYWmJDbVUzTmQrUldTajE4CkhKb3NWUk5Rd0tUc0hSbnVsbS8v
            SEtJd2x0ejJleTdOcG9lNGhoUWFGWWsKLS0tIEtvOWwwTlp5NTJzbXNHUjJBWWpo
            bHBkL1FNT1lVb1hxdWlGeEE1ZS94dFUKw75RlSKS04eqJ2OzoVdhMXg4yEMdZs3a
            8gMbtgB95YqG12Hfk9oRIL/m7OJtCLw75qOAIHkoqcMFzoNkNUmn4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T18:35:03Z"
    mac: ENC[AES256_GCM,data:kq4lVYJYplZfScQo1NSLbRIC0S92KYAUVcXNbbzxGwyAzBx7Qd9T7jyOxRQ6NJgMiq2Wcid2Il79QyQG1J23HZP2R8I4RGlPmGHBp6PWJxO1Yk1kXxiDIqPHnPZrXfNv70WUklY1DYSbkO6u3VfRK6ck+6cRfF6Zo1RDb8sTj+M=,iv:2TFoM2QZxmJsjgY/bBV6bRvG7uuD5ioVTXQrq3GOW1E=,tag:w2/7xqV+iAB8h51XUUw/vg==,type:str]
    version: 3.13.2
