apiVersion: v1
kind: Secret
metadata:
    name: blueprint-auth-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:THt8SUtfjWXJlCXk698pqsKtUqky5W9l79g4E7kuBZTwrKzSqczVDrXIDE+nPTmXd3htL5n06xNrIusu6MXFY5ZHOA==,iv:M9lwy+ILR5MlWM8Faie44f/lFc5i5bF5aTO99UWSP78=,tag:avQKqmBFnVkmfTUSIDi6Zg==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:4nJknUrIX4MoSp09OQ0iaRkJAY+2dvAXlqshsCBY,iv:0EgWeuPBYUc/c2Ma9RmwrokrwNvaANT3cBl0Mce6UNo=,tag:ajt62MiPzIfRy8Mvh5Lxlw==,type:str]
    WEBHOOK_SECRET_TOKEN: ENC[AES256_GCM,data:x1OUhokq6sQy35XeSncnLIDSN1NVO2BnLzo=,iv:JrnBFqGegdZvly0uj1HWmIbClGOv27GIuRiS8ru6Oxk=,tag:RSe+aVy8FFLRNQkf/ijGgw==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:kuur2/CcI8E=,iv:2LH7nRXDEbxrdVLOi9ykyp+R2WBcosvpKVjS3Z5hmwA=,tag:8IZlcKXIXV9GVm1g0ugYmQ==,type:str]
    SMTP_USER: ""
    SMTP_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ1NrUDVUQUEzT0MwSmVz
            ZUZ0V2NwM1FUS2lJUEVKWXFEZ0ZxZEFCREhRCnZ3bVdMWlZldG43SmNYaURRSFI4
            WFdwdXl5WTJkRzhhTkpoVEV3V0tvT3MKLS0tIGNIR0FYYkl4bUo4TmhuMVNZcFYr
            cmhpMm1KZS9DYUpsL2JaZ1dFRmFibzAKUE5jpEhkqo5kwM3NEP4hm+FwmVfzqLZJ
            c+3VZ1d+tieu57r9pEvzPR1mX5g6wL/KnvYY5zdPVwfK/6s4vfmaRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:33:26Z"
    mac: ENC[AES256_GCM,data:od2UDUKj7bbd64pXuUGJrf4Pu794QBLdh2eDxqRr2H3GYQx+n4GmSAGJlrXcWQWcSHnPATLWIxYtMEFesqRatm5ZcfFv6B5znwVd6mf/8NnmUFgVhtv+uVSHhYlt82U54AIpnvvJc8RqV4mEdN+qyI4YIdQfHLjTxn4S2AEpopU=,iv:PCaJ0lPuKs1PbISvdlr04x90MV7sKmoVe75TfGvDp/4=,tag:+hyee6ZtSRf3AfkYr3lQIg==,type:str]
    version: 3.13.2
