apiVersion: v1
kind: Secret
metadata:
    name: blueprint-auth-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:etuIVK46VJR95RlL2Vd02HTcxMRnCM4Yo+bbqPSSZ4BewFv2ktcIcMcUKyF5BKN8V9pNxuXA5f4KOZlga+WFvXRReA==,iv:n++04X41gK19hDWtegMV4QeqCfQTLpmaHkMopbqwGok=,tag:VxssVPJt98NA8ubLMEmSVw==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:TlURXNdzboEu6aSSEJFDxg4vjWlWxMpPGTuLW+v5,iv:hI8hQQ62B4UKMXjiA/gda7t7M4Pg8VJKALTCrTmGI5E=,tag:r4KVikVSQJevfDHo98JF2g==,type:str]
    WEBHOOK_SECRET_TOKEN: ENC[AES256_GCM,data:fsVe0xBv3Z8KC3S3X6HpHAizKRRvqCHdtzY=,iv:WQbsTklKVnNtgAR/0B5XoB88Up4an7Kwt1QnGDHqLmA=,tag:3xkt3rD/yg8u0KxSt07mPg==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:k3mKnW2s6Uc=,iv:0AO4hh1qUnN0p4H5XC2PCnJExPbXuuRzi2Fa8ZyPIHU=,tag:05KFVlGo8jD8F83Wt7deIA==,type:str]
    SMTP_USER: ""
    SMTP_PASSWORD: ""
    INTERNAL_API_TOKEN: ENC[AES256_GCM,data:DVgHh1XsjwykhwunQlgFBQD3kA8YuaxvyjZv/MNqJ4R5QTnCq2m8P10I6A==,iv:sPckG3TVPv6hIa4EicKGWihuiY/iPTZxymTz9u4C1vM=,tag:3+KgWDpGiwywRsxe4B+fsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMVVtUm5UUmI0ZzNjUHpz
            aUo1LzdIYmR6VGdJV2gxZ3RLVVRJZWtaSkY0CkV0OTU3U3o5d0ZPbEU0WmZhK2hm
            UDE1cXZoVWUvOUVBZ0tpS1BONDgyZnMKLS0tIFJ2OTlaSS9oa09tNVUvUlU0MTQ1
            T24wM1QwNElKMk1EZkh6UGhDb2c1Q28KVEKWj1loCCam52EHaAJIbkAk4yXwWLpS
            7G6pMlPiUZnoZ2659izYwi5H3VdPcfcdWYovatLjM9N6uDRG2SQj7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T11:21:53Z"
    mac: ENC[AES256_GCM,data:C0ZGmM4Ghk5B0B8EZUc0P7V2ppd8Dl//JLQlWjWn3qFdXpf9MedFK6tryozpYsNhENLyp3HhTNf2kTd0fWsqyBqvVmjYaYxytQd1KHPFjJ7uAlRStN5yI+MvlW60oBX6AWzJL8JBfo5lZ29tehGmTGUY6RBUW3alW2ipe+Hb+L0=,iv:AI2ZFxPgxtQoVvPGdy1h5xkdGzy0UvdPWMm4NSEBUM4=,tag:KNFi6IQCL30rlPtmU7Es6w==,type:str]
    version: 3.13.2
