apiVersion: v1
kind: Secret
metadata:
    name: blueprint-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ZbOfZeGswOT9PkaKvNmgGGumvjVlK4AwKGFAwPpWspcM4184KSwywHJyu65uIsF4Kld6H3Ze8kzD4Dm4S9C4iYx9pZ9fXpuAgKEfs880yKWq6bJm9I4dt2afkBYLwLvGiWwMHg==,iv:qoCaIBAmrbFXxJaMjaLqAMgPhAKkFXdi4J6/XGi2i5Y=,tag:8h78HTrCQv2q31SmAls45w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:5YARaRFkXYw4Z7H9YGKWvOmuqZPYIlmMuL4yb8+xT7A=,iv:Akw6HLcdTOkCCrB5naYOHgnSUootMSf2eH+mu4ExUm0=,tag:PdgrmSK7ZJKPy8t9Vcc1UA==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:3aQ/zn6HX46ebJaGJ5l3re16G4J/ZCHjGZI+6F7QSm/A,iv:6bEApBxcNtkSHM1gSRtEErAteZWVELKM2qk+cVEJQAQ=,tag:kvtlc6aHm0GF7VyqOcmSJA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:Qjj1MCUiDkH03w==,iv:AMhWX2omnc0M60F+ucACOaPe+IT983mVSU+jrnD4Y1Q=,tag:LjegjHb2hxhS0zSCVfNqpQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:B2wuOF0URm751A==,iv:GE2j8HQMsFyF/vt2DjPA3KODZ1gOjI7PRZg6J5opkJc=,tag:BigQk6viFgtkqTDv6MPkBg==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:dIaApa6slnXsunb7vHg=,iv:P29v/Ww4eKVAjXt4130tpNjLIm7Ehd9sKkHbC6wFtZY=,tag:RiutZqj7KDf9qa0OcA37Jg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ImTAVXiSDN2OVn2kICANkPpL,iv:sYx9AGLeV0CVQv3evrj96mAIgDFNvPI6OMjvPoR2dtA=,tag:e4loqmyDjPaldxTgOJlcVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNzFscXluaG9pZFlFbEpT
            UHdJRi9Uc3VRejBMRFlrVHc2aTU1N01kc0RnCmNrQzAzbk16dElPclVtUzFpcStK
            dTFjL1J1dnU3b1VhYndiMlU3UVVhMFEKLS0tIDJRNEo3Q1dlVENSdGlKeWdyWlZY
            NmFvcm1OWWZQaVlmVWY3MEg2QU8yZ2sKgpVbP2g3T9lc0pfiCO/9UT06sy8dYyXf
            qCc9S43LzVjd2HyupMA6NMNC61QUYtxCxCCk6m06QseWHJue1a/9Hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:15Z"
    mac: ENC[AES256_GCM,data:EgSUd0cV+ttR8RTU8gTExwWpGSCa5tLMUvcY2M6CcXSRx3h0n5OPa+IO11dsj4CChP3G5RWmassPvORuPRGhVDAtCw+ljqi0MjBx864kZAVpWbnS42KRW2cJu8MdQw/hdFiws8eCd0Ybx1o5FNm245+qxzqaV9JTvIMQ8pIn2UA=,iv:cxnk+eyBM5fiELBHSm6mIga0M2U5rFeKtgg6xFzJwx8=,tag:KItj1nwXAoBpm2oxJBKubA==,type:str]
    version: 3.13.2
