apiVersion: v1
kind: Secret
metadata:
    name: blueprint-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:rVLUwL0XtT9D5z/1U+5q+MPz0DIHbfPAKloD/n6Y681gjwRV1NxX7ztstX8plOePhMkkNUDiJJY/Ik1+Xp5dRw==,iv:zzFkj+312zVO8RbP/NYwUk4f9rs0JSY352M7Avzom2s=,tag:8O+SeqjZ5P3J06fY9ZxajQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:AUrEdeBaldk/O8GleaWqg/0VBGmxpBfIkw==,iv:HBxkPQvXcFw1hSx6i3KXIEFC3e+Q89bCHow2KbWKyU0=,tag:TjopDldukUrgPwmZB2WLQw==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:hlxEfGnRtFJT5GNUbpcnLuURJyCT/8prkPzVZShkSQ4e,iv:6+arYQMV3yzo2e9/6jzyoiY/cO/Pji8q8MbgD79icuw=,tag:4DkpxV1pcAWKR7n1OVw0fw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:fxfJGLGuUSdGxA==,iv:/9mrXSzNdVxKnJ9TDivux1JBAK9ETMS8UUjt7k/lOVY=,tag:ph/f7JLtJMZvv3MOdtVcCA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:7vmywuxb7WxN3A==,iv:U16YGlLWTBbUN+ygLtOoA+3sIVl+d/cNyRJb/DeSuMU=,tag:NQVlqItEAIRP40R7A4mcug==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:qQsOtqBio8f19kSeKd0=,iv:Yj8jn/EwxY0BfsG14zElEj6FhUPKsQgwkveBsc8ZqCE=,tag:iNGH0hecBqYZ3ng36U60Dg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:swM/ZGDqiW8CG31d0u+oznve,iv:d4E0mQYfAqtgsHVGjY2C3kdZbAW0BW8FDpRSYRh8MeM=,tag:OxUQjqXInxWlCI5RajMnZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcUZNalN5dlVjY3lFZFkx
            WVNHS2hLQi9jSVVybkhyYjl0TFRSZG01SG5RCk9IemxBU2RUeXA2S25kdFh0dEo5
            RlFYK0duQ3BOdHpDR1hGRFdsRmVFUVEKLS0tIEF2TkY5RmZIaVFSbjJZNG5jQnVZ
            cGUxN0NJbmxnOUY0S0x2ZjRwV1UwQWcKUQohNhVoyRU8rXaonXP8ctWRbAEYu6v6
            8rB8ySOzzVn0EjN8L4crJdAuSHOPJZc+/0pqn5H1jWgiLWtSWCBWNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:38:02Z"
    mac: ENC[AES256_GCM,data:LcOE4ZmdMe0XFZDre+pDwUIvWLNOm66Eu0oghr6gtsYcN3Qnfdh/NDJPGd5lHuPf2GYtNwT+xiSIKDS/NKGkanP63tU+KG4sdx3pb2XTk8vxyu/xqbTrNlFrnA56NwZqWYjh4qqKD3YX2kVeKE42YZLLAq6ruzEluEx/btjlocM=,iv:I1x75F7VW9XXiDL6djVZWjAtppAVcDuSWruF7KSouw4=,tag:N1WNUApgrlAl9oHY2WK1pw==,type:str]
    version: 3.13.2
