apiVersion: v1
kind: Secret
metadata:
    name: blueprint-auth-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:U9LkXaFyvez3hAlciNYe1ptcYZVjSSF4OEwM6cpz1XZcpHSj4plW/txfi7/zFl6GnSCiBqgOdn5iqtn/gEXLbI37BPM=,iv:rel5NXnTnY+Kl3o9SidRqyLw5ERYFlsxV6v8hYHLscY=,tag:UgTl+T5i/6E9sspspWvi8g==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:VKvBr3vA8eYN11L6+JYCn0IFeiGhmrN5DgQ66IrauCW2lS00FIZHVqRZ1pLzLUy9rRJsmPTBU/r4OEdqFhXHYd8y2GQNOOdMPEWKDex85yi1ygUa8ttU3QNE8TAGuj31B9xh2/f5EM48GrdS7EOO6+b3EbukqRlmhx7qtoHeQO6Sab46LJ9AWzNi/LMtxLmA8+edOKuV4wTuZU2LIaP3aZ60tHU1uDQFrcA2+Q==,iv:wcNLpEO0VaU/BqkhM0LHnKbNf3T24uBOVc6WLc5Dtzk=,tag:ncpIcR9G+6XHU8gngrszqw==,type:str]
    WEBHOOK_SECRET_TOKEN: ENC[AES256_GCM,data:Gg2ArEXlLbROVi1Wl7k2pRvK5BcIiraKpwNa1EHQQjc8HZB1zV8g/TXRUFVuLPJBRUSgwwFXFVmwnEQeyezHPtN7BwP7wefnNCSh02cYBX8VQgmaQWsDLZz1AkfVHUd7sFwK/s5U1cZ4q4BOja32Mj+sJh/CA05YbhqAM7j2e3OCD7t4tKBoc0c7kJ4LozF6OPV7RvCD96SfVRAqOmJaRY+1+DuZaiQBfJfuNw==,iv:FYmfBzIE7BpL1AjCiRZ/HCTThgb7rGV9w7ahg0Ldh3k=,tag:V3wmdRqVJ3gzeyxXM8uWJw==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:LAIDzswpxDI=,iv:NnSmejZGiRZL3GwviPT8SFtuWcBdIg0tgYyJRsTqUMw=,tag:i4EwAFeLtTQIDPTL2oHIEA==,type:str]
    SMTP_USER: ""
    SMTP_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZUppUXNnSmNnMTBtamRQ
            RmM2SGs1UXdEc2VGWC9tWEFyTFpIbGtmcVZFCjNJTnVNdDR4dHF0MVBDQ3ZCWlho
            NUpkbDU5TGJXRDc2U3Q3eW9EVllUYW8KLS0tIFc2SjRSNFFPbDBEdm9TSkpiMDFM
            R2xLT1FqUzVDVnYwYW94ejBlOU1BVWMKhTqkY2xc+GP+18KdnTFfP2dD4LqC9CPU
            9LqF19J3RW8DfKaEFeoH2HAbTY/F2oCKiNMc9OuiSrtttKRBTzdqug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:33:26Z"
    mac: ENC[AES256_GCM,data:5XoowwyDhs8r40hS7gDK+mC1osDJxj1NXTsgtqnxh0PhdeOEib2hie9tPUEmq+8R44ih3NZNLqunLxTmK3ZykwDTupxydYfLNi64FVH3TRZUyQXi6BEzDdgRCMRXei6hrsUDaK8yGIiVao8dFrWN+m8LlJGdIgCa84ZfmXYSEoE=,iv:8rtcnPzksWH1fAWga0jA9Xi9pXCO2lLi1ma0toFXpJQ=,tag:fTGgcur8tFKN+fIBbWS83A==,type:str]
    version: 3.13.2
