creation_rules:
  - path_regex: apps[\\/].*[\\/]overlays[\\/].*[\\/]secret\.enc\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
  - path_regex: apps[\\/].*[\\/]secret\.enc\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
