apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueprint-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueprint-auth
  template:
    metadata:
      labels:
        app: blueprint-auth
    spec:
      containers:
        - name: blueprint-auth
          image: maiconlanzendorf/blueprint-auth:0.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3400
          envFrom:
            - configMapRef:
                name: blueprint-auth-config
            - secretRef:
                name: blueprint-auth-secret
          readinessProbe:
            tcpSocket:
              port: 3400
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3400
            initialDelaySeconds: 30
            periodSeconds: 20
