apiVersion: v1
kind: Secret
metadata:
    name: postgres-prod-auth
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:vSt4vcn47hqPCs9w1BS8UIXZi4rdEEe9RhTYYPirKxQcfwXF3OmnCtfMLg==,iv:q690cleLWV3xsXA99n7XNf8OcX1mcdYxiTofRxgFZy8=,tag:8xxi2TluN5YpiI7s1jEXbQ==,type:str]
    password: ENC[AES256_GCM,data:WUnzQb+OgZGjusrwXO4tR/8+JP0zJ+WnKM2VBiXGrMQmh8ohHWvZTPAdhA==,iv:nVPb5Xe7+At2/i2HYt4nJChVqThb1xROF2r/zWAmvIg=,tag:L3VTtX3zmaSry6DLI/r85g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVGpFN0NXSDhObm4zek5E
            ZjF0ekR6NngreW9BeUpCWlFWeGIvQlRFQ3g0ClF1VTZpYUYvQXVMOEVtLzhqQXpH
            Y3VuRlJtdFFDS0Q3ZlA4QTNWcE04WG8KLS0tIDRpOCtkNUlpZFNrVU5jVVdwRzhV
            VHpld0VTREl2WjN5cG43Z3hha3FBbEUKfvzK/iuh1iFpE06orZvsQGMOjuGWIG7t
            WIvPiB9zKyaCkdL7sCrAwewOz2LmnKlY3p5cr4t1Rn7PDGF80VsuTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T15:55:31Z"
    mac: ENC[AES256_GCM,data:5knl58JSCYYHn8ql4mmOfRtnCMQHpeN3tZR7Ig9pAeFgogBDPA8Vf1AHNhhhABRQrxfPOGRtLorGaeol/rufTweAi4Ojy+P8tiwobD5p0ElqlFoHRPG1ElHxRwsK8WGH9iTGbcxKcowtQm7IuXauS5eh9y7fBUkEF8aLrSH1hig=,iv:d+1zzcNDokx3nYC+Lt0bvXqNvJO0Wo1yEXe449PmSbM=,tag:9hy68UINKvGIE6N0eu+b8Q==,type:str]
    version: 3.13.2
