apiVersion: v1
kind: ConfigMap
metadata:
  name: blueprint-config
data:
  PORT: "3333"
  API_URL: https://api.blueprint-dev.local
  BACKEND_URL: https://api.blueprint-dev.local
  FRONTEND_URL: https://blueprint-dev.local
  S3_ENDPOINT: http://minio.tools.svc.cluster.local:9000
  S3_BUCKET: blueprint
  S3_PUBLIC_URL: http://minio.tools.svc.cluster.local:9000
  S3_REGION: us-east-1
  S3_PUBLIC_ENDPOINT: http://minio.tools.svc.cluster.local:9000
  SMTP_HOST: smtp-dev.local
  SMTP_PORT: "587"
  SMTP_FROM: blueprint-dev@local.dev