apiVersion: v1
kind: Secret
metadata:
  name: blueprint-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://app:apppass@postgres-dev-postgresql:5432/appdb-dev
  JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
  JWT_REFRESH_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
  S3_ACCESS_KEY: minioadmin
  S3_SECRET_KEY: minioadmin
  SMTP_USERNAME: dev-smtp-user
  SMTP_PASSWORD: dev-smtp-password