apiVersion: v1
kind: Secret
metadata:
    name: blueprint-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Hqqtw7zro0N4rBagNHWu5xUAzEWTwG43iZK8WUqhNNZsPimypvKQCF68sBPdf7ytxbQYzv6PG95VrmgFmrIxX8Gzbw==,iv:gTXZ4mLrZNW3o0m2hzFJPWk6vzOOF04rYcDtRDjKp5c=,tag:zvwIA/0W5kQtfJQNJtbMZQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:q8nIf7Z+ZsiDkvepdmNTz+63lcjeg8h4rScF58hChd3CgL6g3owDS64hLzDLMYDZDRavblPDMkNEYVT6yzmJ/D78dxh0KmXdXp4mNX2Qw1uqpeuJEMC/1iPo5Yp/+MVYkSSNk4TgCIs25ubcCpBU3zKD96pCZiZ6XliyasS3Xhrea5GUl/Mp0CKNm9m551bbCA0+bSUqamotrl1DN3/6dKEF+NfJg3V1HE4ltw==,iv:7Ik6qTvmfGzGcmlp7I4DI5vG27FJ8/qYZRaNFFBYZ94=,tag:Kte1Ih2BZhYJk8vgFOPxCw==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:0cljQgf4emP6JBHq2973v7n2hIco/5sAqJhpX7V1w3jbLLwoNprZoPQGaSE0u9Jgk0IwTiLkrtHTNXBwb+tR9/nX7CGAKCGn3cbT4c8cUHdv4m/dh4AInNrvs3SKPa/VVRcJ7mrSKKh4ox12bI6+EowZpq8qa5KaNhfCbNKGZ9UTLBHEFsEYiAYghsx++QKgf3RAZA7r29IbDgTlQGHu6gebis6Yc1xU8H5KGQ==,iv:AVYgqiCm9t73XYHM42J+LGgAQcMSrqrM+CICt4JAnNQ=,tag:ena6QiU2jufTe6+DR7SdHA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:fHBAyUljJvENbQ==,iv:sWwDEAD6ahbTCDYK8G1cCUoVmqRSZ8vmq7qdK0P7AvI=,tag:OCwMf5ERPP0+uHjT3oXjNQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:ocYMuTmVsQ/hOA==,iv:ZXQIaT3tyzCWb/xLFv1L1Fs5MHnfxE4SSVoSjwfhF7g=,tag:GhkpnC1BYihNzZ1P3ZNs/Q==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:i0ZR7iNn6ugcAFhpOQ==,iv:Mo3klu1c/hbbXYHnMrxDVByEZADYkeygoMgUp7aWxKQ=,tag:QQ5DKmp4LuNLix88RmJ6AA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:yxMjAfnvPGBfhIzKhsFLTbE=,iv:zKIMNNu04OcZMHCJ3v7JWq1sEfZUvPuDMDg5AaQRvCk=,tag:2hy2jprCqawlJQJnjDAkpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS3Q0VWpQQWp5QnJSNU9t
            Sk1YNGdHdk1ScWFLUThRWmdFTEVVYnU5Q0Q0CmxPcmR2ZitZZFJ3czBMZDlsZkZs
            S0lQNXZCNFd1TTI5N2lOYTc3WFBDeDAKLS0tIDM0aUJIS1lhclpZajRZb1N2RnlK
            UVpWS1pTRmw5K2x3ajhDTFpNUHJJTFEKBih2eS5NuPwx4NAHrZLhtHg38S1L7iwN
            FKeevsfEgYKB/FO7RqLsMg4pZ9/UkW2eDnLmTI6RlZg8mRbNCKwKvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:38:02Z"
    mac: ENC[AES256_GCM,data:rref2L7mXgRvZST9uA9gUVrW3xkNxLBL/xT++fDb6CyRlQoLT0W21E+lfsbxcODN3a2DZc1nZD4fURdq3BHzHhRiaQMsaWATtjn/PK8/z5QMAid7OLL2tT94AHfLOu2vRvTzxjbN6ZwyKZjZn/6eTt5zCZop3IMxyzT3NsL5cYU=,iv:9g+vuy48HIqR9odM64sfLrw4VS/j+N+/MbwY7HZ6guI=,tag:STSDre5tFpBuZ8fCWS3SFA==,type:str]
    version: 3.13.2
