apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blueprint-frontend
spec:
  ingressClassName: traefik
  rules:
    - host: blueprint-qa.local.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blueprint-frontend
                port:
                  number: 80
    - host: blueprint-qa.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blueprint-frontend
                port:
                  number: 80