apiVersion: v1
kind: Secret
metadata:
    name: blueprint-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:5aL3YQpm19vahdrFXOUI29HZ0V+Vw0chTEPvFGhlSObiheu2S+UWgI99bPx75o9200jd5MQMKP34lXzdGnbtozw=,iv:S7uEadODC3piowLfkJmKYEg9hgOVFyO8ZuWUvlrYTcc=,tag:fgW2r3nCc02Q9zb6D2f+QA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Mq0kvusT6gNx0bojQMbpWGUM204Hv1o=,iv:8f+4WxqMeeSPSogCx3NhUSiRWBWZi2t6oYgvlKgU93E=,tag:34GagWsj/FH6eCK7GM+a9w==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:vumJ8WIp4YS9f4DupYYd1cHsS+RMnUHnVcTiy8xwoA==,iv:cTyJNEhyN2Pij8vbz3KTmitmMiCxRhXEiO8XnZ12uK4=,tag:t3ufBRRoIi3DtxiGRLK38w==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:yLcbd3vCPuVdIg==,iv:nAnHXotXLBL6CDZ9aXDCG9vhkA21r5Gm/mYqg7QsPzU=,tag:V4h99E2lC1hoRWc72TyJ5w==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:JlI33eNozM0Vdg==,iv:pU4TocWjC3Zg4iUCN3eFTIm//Wly7VpJ5j06F2J3iBY=,tag:1a/wRNkkYL69YU8zEN1Wxg==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:S5GVcJZqvaaBSjdc,iv:HStiNUfF3myiYxd3XkEq5aO76/yl1ZQ7ThZIwTf3CJI=,tag:Ffq2UliQIqRqAfu84ccKXw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:vfehf4PWaj6EGXFZhQGhPQ==,iv:/4ubvxNZLM9MaGlDq2mU+YTB2gGvre/hFWeN7z0vX6w=,tag:K7v61zoC0VZA4TUtpdJJFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eFh0YnFzY0NGNmJvS3Y0
            b2VWN1F0RmQyZm9JQndoNFNwd1pUQ0srMnpJCnFRRjdwM2U0OWJrd2ZzMmNtdTd2
            cmRkdXBvQ3VGMS91SG00cXNOaXZUeWMKLS0tIEZkTXppeU0ybktxaFlsVExrTitD
            ZmJyN0Jla1hKZURFUURJbklTU2ZTaVUKJLnTYmiR4vsTEMnY0eIyuAmT5HcElad1
            USgotdAozo5mszBqliiC1sEedtxm04CE7rpGRZJ8yD89BvTmSqnWqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:38:02Z"
    mac: ENC[AES256_GCM,data:M6yU3W7yeqWtXhAaDapKfPAbhoOY4P3tnpXI3aZ6k7uMKDtovH+DK3IC+nLaOHbilzDUbPe5ZInQMlRLE6ulYWdlodmDGM4JoqAs4TTXFtmRHxO4RecHr/YD5Xu/8NO4kmGQtKOmZeDHaBg/F2/uazOWC694i1q6gTOLErYGbjE=,iv:yyzLp1an+EQ8ybvuysInZEkQgKYBGypgkEzzAeULOVA=,tag:w/aBT3uUON+xJYreoYQyqA==,type:str]
    version: 3.13.2
