apiVersion: v1
kind: Secret
metadata:
    name: blueprint-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:WpJaTzLlASdSc5zk7aAVFUi/bWsv2IHfI3GKxBHeqmcr9vbDZXNamhXY/6Wfp6mivm+Th8R+jmJ695o+uGtfPCc=,iv:oHFbakmBYfg7VUTgPAh59GVhJQp8JDPqy4EqkpK43U0=,tag:J+U1sdD9uPd0KlX6Pi/iKg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:1Rp5Xqlr/CnP3gNKW32u83VS90PNyM6G9Lkp2dUuQgkS1jz0CaUfLOGmJJsEqBjAijU4hOSdAhYhF9oDFjnX1w==,iv:Jw8LUNr/sLy7Ss6UIIpjvse6y5vC5pGoo6hdMUg0sOs=,tag:FCq42HaQp5qyKXguxpooEA==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:iqGIEpBSawcuuxJGn2RySPaa28MuPQ6DumqIo/eN9FU9HpHRW4Bq1OeI7eh3nXJKEv1wBxC62nHFB1FwxwY6IA==,iv:gKfuWIfuwzArCmSVs30zBgDuAqg/+XqyFFev8tgExwA=,tag:cRJq4O9HuastukeEIiBXNA==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:eREaB0Egz/eEyA==,iv:IDMOioEvt85R1rqyhZIvNqo7fjoJJ8BfYN7D0IN5Gls=,tag:va88/qHp3uixu7UNXTks3A==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:6TPCwHKbe2OKKQ==,iv:LhaMZCLVbD9GrlFJMXoOPzXHe6OfBBR0sL6lNSpnroE=,tag:Ld2njq8/BVZWoVWWgV30nw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:XToA59+vlQd9iqu0,iv:dkRjbJUgZ3qWQOfPhETp8GIrQHP6w1ZdhVkn0bMVAy0=,tag:Yy+l0OgNm/YVqgdBDmffdQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:H08eyrCNEpLdjerjv4vu7A==,iv:RsIobwoELCvHmylsjC/tn+AszI54BnxSk+mtCQl9CEM=,tag:Y1Krblsy3FPAqoHYZ5MRvA==,type:str]
    CHAT_EMBED_SHARED_SECRET: ENC[AES256_GCM,data:yxzlE9ZbF3Fso+QeeZc60JK3QMu/MrwsmHe5oEUR9nfXvJG1SNzV9RMefjrsGgYMF8JI4gIDHZeXdVN+pgshHA==,iv:+n5hvhTb+VaDSOCRgkvkwQCulvELnToVTdzSyWj2rdU=,tag:eCEXpM9n4w9cq9Gtm83EgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VGYrVTc3R0FvOXlVcm5W
            Rm5YVGcxSDUvZWhWcDVLaWR4WWNCVUdXenhjCk9EMGZwR0t1ZlliRDQzdGRqT0s3
            cTlEK1pGTE9vNXdEU3gvV0FMbmVkbDQKLS0tIEUvUEZ0Mm82bGRYZFlKdm9Hdzlr
            VkdkUVFoVXRNcGY3Z2RJNkJwYTVDT1kKRtG4G8XL97IGbSvmo6BTb3FVw+i04dnv
            U/TuPSyxQuQqI7TRmuyyBIwq/+U3ItfQ/qD4lm6tMdAd/r5qBfy0EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T18:35:03Z"
    mac: ENC[AES256_GCM,data:asRlGjNKtCCqbunIqqZoCr5bTfItS2ji9EMwSJEVgr6kBSpXFwHQHY5wnMrJjqZguBiglvgAdq6FLrn8Lvw3k+kjdOEC9kfB1xZrHbHj22jVsntfAzTG+aWrmntLlwAVj7CEj+ENhdJ3xoYKeW00i0Y3Le3gSgMZViOCCkiOlxY=,iv:kBLSbJ0rDbZdeJI0Trac0xmyJK7KYAsp6dW/Mkbeu8k=,tag:Oe3fhXQpVzdizEQdN61g8A==,type:str]
    version: 3.13.2
