apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blueprint
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
          - env: qa
            namespace: qa
          - env: prod
            namespace: prod
  template:
    metadata:
      name: blueprint-{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/Global-lanz/gitops.git
        targetRevision: main
        path: apps/blueprint/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true