apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Global-lanz/gitops.git
    targetRevision: main
    path: apps/tools/pgadmin

  destination:
    server: https://kubernetes.default.svc
    namespace: tools

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true