apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:ZaoNcAU2kw==,iv:FIepsDsQvI+Ll3UomDtUJYhjMQ3JBJTfDXHfWByjmag=,tag:OG7EotqmawYOHR0qmNasxg==,type:str]
    N8N_SMTP_USER: ENC[AES256_GCM,data:MS9hEo/3LPOSbMpBFg==,iv:zF/VpSjUyZTLwSk1NdeU4VC3SO48NgH4DO0AQVFZxvs=,tag:SuHyxMSWBvy2rTaCwY52jA==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:PSHOlZCHA373WMkfOlDCKPM=,iv:LG3QlrIzvWPfs/sEznB+e3TN68qzFN38WgyhnS+xmQc=,tag:DofmNb2Np544wmHprz7AXg==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:TrVlublDVKNLimw+4h3YE9URJG9KvGtf9KGtHUpMJ0s=,iv:KiJThOJNQt6j8jJFoAQyCzBuMfvhCTbevnQydN5CcDw=,tag:o9EXnFPlrecn0OaDzpQlFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQndkcis5cDd6TWtjV2JG
            NWdsc3JQMytmU0dTdGovd0ZsMHFXUWhwa25BCm1HZUIwcnFIczEyVWJVRExod0pE
            blRRMUkzUU1STWcxbGdMQjMzNFl0czQKLS0tIDdMejk1alVRbXNGVU9MWkFRU2xv
            d0xGMDFiaXU1Z1pkZjBBbC85TlhZOUUKqDcjbRmqIz7L51+pA9g6DKoMDg+eljhE
            fnZSwH2Z9XQNBxVbBN367xfEPrxzZ/xa6WNk2n0YCyAJ1E/2A7gung==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:33:26Z"
    mac: ENC[AES256_GCM,data:bE/AZnowClEwuV6ArLCJjpiTauB4271wwV/w0J9dNiBDY+CeNsD2uU6i1N1NZInina2e5eGuNCajpMe4vpIPjJ5W1LV7IFrZ+DpHeWJS2TJbNyhHmG1GkR2uemy+zksyF0gBztF3/LUip20F3aQcbazsPXI2lUp7Ldk3FFiF0z0=,iv:zdWdzYmsswm1c5kh+9MKvfjXxiwfpB96SOTWEm2sOFw=,tag:JWjiDtRrLX5rUtHNSNqqJA==,type:str]
    version: 3.13.2
