apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:TgY/G1gylA==,iv:lta22tRsJDiBbaOze/MHGq/z1UDNDilKl+vMgqN7OnA=,tag:qJlFepoCwDL3gb1ZacQikA==,type:str]
    N8N_SMTP_USER: ENC[AES256_GCM,data:z+imDaJ/ZiaCQT06RUE=,iv:VtXeVymosJKo0bY51q7iDsNUbNgvWHKlyzDoiFOjjtM=,tag:FtE8B7bUo4fLmnR71PK2WQ==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:kb/FnDWLfUYmriYevbVTSrpG,iv:KODsKbtITQegFxLLlBKsg51Umkek9Mhguf/hNm4SHXU=,tag:Nm95u2V26GWbKoQgcOUvHg==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:VG5vCeK2poAA2VDOQys8A6RMkiMOiC7cFN7KltDcjuVz,iv:9y0jYnI2OLEZMVBi5CZbWpDcmpCKioBGT50p9qZion0=,tag:pGnrenkBGoX/Mt9RiO8uHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSVo1S0hmSjJidE15OE8r
            TGFyc0hYeWlUbzJOVEt5L0VweXhYK3ptTURVCitrMEFsdi9KN2wrSW56MUZlWUxV
            ZktIVENHcWt4UCtPY3RBZEc0Yk5Ba2MKLS0tIEhCczhXN0hPaDFkYXh2MnFsNmJX
            MUp1SytvZkZxS3lQeU5GcjVjam9Fd2cKnwNjSttLymfRDBL5K31B2OszLREnggvr
            3UJI5EBno76Pg3IeIfAupwE5o+kxRSU4Iny5EdRNVaOR+7GAcb0hEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:33:26Z"
    mac: ENC[AES256_GCM,data:TFOxAZxr2/AJ7QGVtnmXFLFbDwazsntq0odob+2Z2faPG3lf5F4g4tdYBdquqIHnJbqkdxhRx7gSy2SBVqT7zSHzI1fa3rA0y4fywppdJJVJvoChPuh0ddIS3bINohBTHc9wtfqUEQrFB9bkCYNKJNAdcD+iFVp77E7mbBUGEFY=,iv:7HRD9qaqlsfdoOveYn1Ed7WH0mrmLbkQRVKjwwE3TcY=,tag:ZpRg6Bbwb9jpNwiiDa1QSQ==,type:str]
    version: 3.13.2
