apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:TgY/G1gylA==,iv:lta22tRsJDiBbaOze/MHGq/z1UDNDilKl+vMgqN7OnA=,tag:qJlFepoCwDL3gb1ZacQikA==,type:str]
    N8N_SMTP_USER: ENC[AES256_GCM,data:z+imDaJ/ZiaCQT06RUE=,iv:VtXeVymosJKo0bY51q7iDsNUbNgvWHKlyzDoiFOjjtM=,tag:FtE8B7bUo4fLmnR71PK2WQ==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:kb/FnDWLfUYmriYevbVTSrpG,iv:KODsKbtITQegFxLLlBKsg51Umkek9Mhguf/hNm4SHXU=,tag:Nm95u2V26GWbKoQgcOUvHg==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:VG5vCeK2poAA2VDOQys8A6RMkiMOiC7cFN7KltDcjuVz,iv:9y0jYnI2OLEZMVBi5CZbWpDcmpCKioBGT50p9qZion0=,tag:pGnrenkBGoX/Mt9RiO8uHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM2VoNUNqb1FEZGxsZjYw
            TWdJVmpORVNjcE10ckJIR0ZCSyt3WnBCVFFNCllhQmt1NVZCQ2gxVTlJSFRnMUxp
            UHlNSWxRSGpnTFpOTjM3NHZxaC9wN3cKLS0tIFdjTnNDc01LODVReWFML01iTGdH
            bGxTVk43YTNYR3hxSC9LN0lFRjBPUXMKh74KMguhGLQNVvWhMe6aRvw5KdEqPHPR
            k2ACq+asGhXzfQhR/eeIsZ2EtPqp7PPrpryPmaqtiJBd5YZmDQjSVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:33:26Z"
    mac: ENC[AES256_GCM,data:TFOxAZxr2/AJ7QGVtnmXFLFbDwazsntq0odob+2Z2faPG3lf5F4g4tdYBdquqIHnJbqkdxhRx7gSy2SBVqT7zSHzI1fa3rA0y4fywppdJJVJvoChPuh0ddIS3bINohBTHc9wtfqUEQrFB9bkCYNKJNAdcD+iFVp77E7mbBUGEFY=,iv:7HRD9qaqlsfdoOveYn1Ed7WH0mrmLbkQRVKjwwE3TcY=,tag:ZpRg6Bbwb9jpNwiiDa1QSQ==,type:str]
    version: 3.13.2
