apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:KeT4FsRk2A==,iv:fQjH3oOW9tk7DeVTAgNw7MF47paJPS6xQrvGV0hdnSY=,tag:1WGXJDmvd9GlNwVJOxTNvg==,type:str]
    N8N_SMTP_USER: ENC[AES256_GCM,data:qOZwkd6ajbZleU71,iv:mDk1CUMhTHCpXn1uePUJpFdupf4YxFRpfwTl1QZXsXs=,tag:3+fiv6A12HaI/LLb1r/QGQ==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:dlWJbFa/Jce/k+NrunKKzQ==,iv:608Ag9Dxk3299Ymq2Pl55eZDkrIv4M8boK87Ixc4uyA=,tag:R/4oFIIm/dr0vjMO0BtEyw==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:dp4pSNIpRGUG99LijoE45duLW+FVtjm5IKsn+y+Z0A==,iv:uer/P8GWLb+HlJORAo2TwTEfbMz+9P2MgSKXXCtuZKE=,tag:TTe4xF0jAfD2Dnxul9dZdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweDBza3gzOW8xLzFoZHFU
            M3U5ZTByNlhLRlRqTjdyWnJvbDJ0UlpnSWlFCnoyS1lTYTRoSzgrMGc5b2VxTGV5
            UUlNUGc4Vm93Z2ovc2l6SVdWdHE0alkKLS0tIHpSQ0JJOW9BM0s5dzZZaCtxTVBV
            bnhlUlE1T29NWmN3cW80aWRZY3NEMk0KPYEstJFp/ea+BERJig3RTLtoC2I0yW4/
            kXmIOdBvJtSJOuDGSoqIEHULcpE6yn/s2iXo0Fo8PbwPnSdm02Fdvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:33:26Z"
    mac: ENC[AES256_GCM,data:sbrSFx7hZAz1ewOZiLmx1xyfSSJmUWNhhZrbqZj0+UH9WEVoCPN/jVvnLLnyEAmPy+I0ilZzucDWDXgby1W727CTfgbLRmNrTE76IYRPutBWJt/sHGJXBWGy3/vBXmkV/xDKc73kEq6po+FHf3LcWx1v/ore3/FwGv3MI/WtOdE=,iv:s0b2jt/iPIz5VsfZ1cqnYSFWN8U2dCD2tMHNShpimZk=,tag:l4Mo9Gmyra1u4asD3pJWhA==,type:str]
    version: 3.13.2
