apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:IH8X9bJQvSW5aJXnCYrn9H9sHcgffvlurEpfms88toY=,iv:76rk/3k7QUWw2F/xoETXD7y30eu0tSvdw4lBHOL3KNE=,tag:koC4XjW4wtq9ujVOxrNj3Q==,type:str]
    password: ENC[AES256_GCM,data:vv5/ID8p3Z3Cqw1SwsGpr6fOxwrE3IDsiFRnvg==,iv:I8V7Zj/XcB63TKQqAQ8L9jb6D92UtGxkX3ZXZxAfT1I=,tag:5R5jXGeG1Zt0mEoAIo1fmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbjYyOVBHRTdQTTdkK08r
            Z1hrZVZIZ0FCdG1USmI3encvcnhTYnhybFZrCmVhWE9NZWE4QjVMdVhUZWduWEEv
            KzFvWVc0b25KQ05KdTh5KzV0QUhzZkUKLS0tIFhrems0UmdEMm51Mm1tNFlSWi83
            dmY2MGp0dDZFcmdqR2dkVjV1TWF0WncKUw6NZBa0UnEWt/WIWuvrGAA5ISVwZlxq
            oByoELxYacl7WCyneTs9ZzqeHnAdkTb1hf/TFCmLgZ1N51o+HrQgIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T20:49:29Z"
    mac: ENC[AES256_GCM,data:vRvWNBnYbdjGvh3JemjMz6Touer16fy64CHHg4oOCbUDwgtIlzLJl4cASnjL/hp1cKQcMKxy2z+Porc42iT1Rs5xtmn+Y3+k+kCKcVMz+Ho3h86707DH1jl9bd52a7qf6XU/sgqzvViiy8RVtejBRnqAzSIZZKMt1+1rpZKLwGI=,iv:56x9tpgGuauG53wD7Azh7T6nCbrXqvNAQ70+ou9VCtY=,tag:gZFRVPyxqgpu5kepWL5uFw==,type:str]
    version: 3.13.2
