apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:EpgXuUOK6AE/RMJsISeO,iv:Vlotn7H7YwSF1621we6nfs5uVLq305BviSJTOHmIfso=,tag:iGr/dsPhltnu/MxoT9pC8A==,type:str]
    password: ENC[AES256_GCM,data:G+E7I5ypbj1fUQ==,iv:CS1DcB6JIodaDKcpFhPVI+olZmsPpR2UBoqd7EFXMdk=,tag:izHGteeaxYKbnpn979FVMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVczRhaDJOSW9zVGhSR0RG
            aFdNaGYrMUpESFJyVWxzQTNoa3JFZmNGdlVjCnFSTThBa050NEJmOHFBd25kajBv
            QU5LWG5wS0NkYU4zb3ZiaUlCbkVZdjAKLS0tIEFLTHZLMnhtZ0VrbTNkdFpLNU12
            a3V3NWZDV29ISmUxT0lqcSs2dHYvdTgKRRbtM3wOlUPyuygdTnJBK1aY1/rfXhpt
            goklzpkBk0MYOU59QHJ89BaizRiji6MtMvIdHJHs0Fgy/JNhi+kVeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:33:26Z"
    mac: ENC[AES256_GCM,data:SojSGh0q37zD1e8flnVOwo0R+pG7NsiAvrvNgEM8iG2TVmXVQZaPw+/0WQOClgTLqrM1jJFC11IhTKX7J6M6Y793aijc7lS2bjk2hKqBEamE9Fz3wgCOtAN8Z0/XXKhH0rsCWW1uysnrjl6lfCkrx95nBqg5E9gW2NVsDpHq03M=,iv:ZJPqb4RLk10z7Bibj5JfL+1uwIIUqWEzueIhsMPeM4Q=,tag:KYTCxrrNHHsgVuB9II4aDQ==,type:str]
    version: 3.13.2
