apiVersion: v1
kind: Secret
metadata:
    name: norteia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:2rb2LTs49BmBn+lk8qDkMEh5eSFAM509HKYfVxWV9y/obHaWe+tNOqPnwfhN5QKjo6/3fQrJMLCrv2ByO6ZP,iv:KemILQH2fXbwDZRta8+yOgmjdyBzjsdtOgklC0vrhmk=,tag:SMj9wbx3kZGr6/XXHoA3gg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:WfAqnWfkYxZ3CWHc2dqviZ7uAfbUe657b8eSLhQ=,iv:8blOFY+SuJda0xfivQr++iu9um+EzFQZJhFkQqXZ32s=,tag:qvJtzc5V0EAeD198Ww1eHA==,type:str]
    INITIAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:jnDLdBaZhls=,iv:j1/YLVCifBUJXwouGv/ROtV1cBRo+UxCr8c4QzHZnt8=,tag:vUk5hYmtGKxpPlVtb0t9cg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRnZNV0ZPbndHY2pNSW50
            aitGWktnMk9aS0dMU3ZIR1JVVlRxMU40NVdrCnFWelhoTVpOQ0U4S0RUVDM2WXAy
            NkJGS2pJNVJNTFFVNFRXbmlZeWR0YkEKLS0tIHpiWXdmbHJ1bE5iZlNlQXVvdHR3
            c2xLcGpFb1NvRjkzZ0d6dkpqd3lmQ0kK/3Odu6CdUSGC3ZfXlov8RU+9Jc41PSr0
            0E9drjyvxbjgTAM7ZHtxx0jaXt5K/B4aNV/NMkvCr3EB77882xwR5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:38:02Z"
    mac: ENC[AES256_GCM,data:Es94bZIzOf7OBuQxn+ibEHZ/RDbYTC1tn1rieKnEDoY68o5RHT3fJNRcMRICkAMzs/cT6XUy9XI8uf3kJgqltnr+IJgUUuYmJkMKxju6+MgvdN5Ye9bp44QVMpGbL87xO+4MXosjrkNjbEtit+/RLxBlxw0ajsxt9kX9ChtmscY=,iv:cjDL+z88OLIm9yZ4XmQi/E5HpliCn4ZAnalPmQ6zsUE=,tag:iKxNknkp+Rn1jPEfLK4cSA==,type:str]
    version: 3.13.2
