apiVersion: v1
kind: Secret
metadata:
    name: blueprint-calendar-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:46YO6j0B+W5J+hCIeT3qRTD3YqIwzJ5nLzyRs/jqIuMgnI5Uv+ZIrpr4219PqD3nfYI9Okyr6saS6AtAH43GxYu0oZ+Wr+g+bt52DO6QmNuJ0IkRJiQ=,iv:DrCNy3H9uLtIcofw/J4EBZWvWICYejySXmLqcO7msGk=,tag:C3Yws91+T6nAybgT98qpoA==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:hftIiKFcld0Msneo1YsI0UEflJBjfAyfERcUH66xFRXOFrHMhTYr4ePdusXhjfL6fiJA0n0cuUSIlWf3nOti/GI=,iv:DqHgXZqf9AdFtySHsX0EH16XWZtByTqaY8rbvweKHas=,tag:z74QJdbeXjQy0Gxd5spRfA==,type:str]
    AUTH_INTERNAL_TOKEN: ENC[AES256_GCM,data:kqv+0pE3O2XsUfDEGL5PpO8uqz3uniX38pBAa2/lMPvbrca2N9yGaT9Z9ieUAxdEPgt0QCatpEIVOyG2ClSlDJxPqmk=,iv:AvESm9XE0cGS03W06GiHIuFKmBZc2CoPgy6h2t3/k6E=,tag:pcF+fyl2uKeeF4li3VEZ3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVamltaFN2cGlPSUhVeHB0
            U3FrVlIyaGtSTjBnWlJlckhnYlNFekMzSXlZCmZreTY4Z0NDL0hUUkJ0N2l3Q0I0
            bHV0dWYrQjRFL2VIM2NCb0JseXBtVEEKLS0tIHI1aE8rOTFZNVRHMkR0dWZUd2Rk
            M3ZFL3JTZXUrVytiTENtVzhzek4yMkkKa0CumfAk10shRN6dh6s310GzESZ0XA34
            OkhjnW/ELOt5boMxhRL27oOTTEQZltRoN6H3zOx0Na3wppW/tUdVUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T10:50:29Z"
    mac: ENC[AES256_GCM,data:2ime6EK/UWsemloDRaxzDkBIW+mON67vhw0bzemJk9W+9wfGz6hdfcn0thGAWPV6lIoc+vUrfTw/xN3FUWhqLtrQPYAaGe0wMZtPOxN56UDb8YSbEkYL9sSDbBKhAEJYv7SxEJJugryIhx5X4SZB8LMIG6WWzCHjXZ+BuwGNi8Q=,iv:JfOduwZB6ygMI2MzdRGw+TtABMCKB/pgT3/vgsB7lTM=,tag:yKoGJZAeImC/WrCRByoSSQ==,type:str]
    version: 3.13.2
