apiVersion: v1
kind: Secret
metadata:
    name: astra-secret
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:GpATzIU7QlcJHmDo57T0JOYwyAU4D5a4+j/VbUknl3JLzA3cyqGiSlqGCE4hqK4+5H5MaYw=,iv:NXCPFyT5EBZx1yva3voYDNnrojsO35b7XSJu5ScmRFI=,tag:HdRyeuafXNTL/lLzyBo2aw==,type:str]
    DB_USER: ENC[AES256_GCM,data:ZZws,iv:39eySJTwUVJoTKdKPng//+gHhAuzdge0AAILL9AS0p8=,tag:IdXzCiJ94kqUXUW/QdTFMw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:pPG3+GA8jw==,iv:r+Jy9kRpnP3I2y3mIIG3yBAFtEmmWHxzEqDxdcF3WnU=,tag:XDWzgyvlc7LhIqsHzjmWzg==,type:str]
    STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:9RFLRXqea9g2MIdF+e5Sl4cKJnd1nPP8QPalgHRwnMg=,iv:4MbXoUxeks0U+8YLcCOsZqDJWAYqmlnoTLee0/p43ag=,tag:JM1MCogmSzrQnVz9c4/DxQ==,type:str]
    STORAGE_SECRET_KEY: ENC[AES256_GCM,data:babDqaVRozOJuTwfjjAd24zI8kqllqXnINkQv54TRD5FqUdUevWwQwHK1tb8hHP4BxjiokX20jYmp6k+nclPNA==,iv:IL3Y0QoA6qk76iMFzCaW1t7Jk5mIGVB3yCZst1UAEJI=,tag:aJiwFVZyLXXUBIFBfSyIIw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:7O6PAb9BFXYmy5vD0RbHQdGIjfvMlQiSkHTpTITIhWCfFDYptih/QNr6QK0IJ3Lqkeps/uPAxDgxP2ff/4+xiw==,iv:Fe+ewLH7D5ibmAc7OT8UZ5AZi0xtmtFyIkj0OibXnVA=,tag:GQyR/u+fk570DE+0s9JANQ==,type:str]
    STAFF_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:FtgvvzQO+RZmQYCR7Of8+DngjiUcUzOmytw=,iv:ti6cTcwZZFLdmVXDHcc35wkBvSAOQBd63F8Tlep23JY=,tag:gzJPqoRtMdFKHOyh2imuOQ==,type:str]
    STAFF_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:Ie05a7vwGErMudQK,iv:/qTpNVoGk4HwTGiqaE9XzX80fa2YC76m0AvDX8uct8g=,tag:G02/iDkakdYITqXZ6E/0NA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ0ZQNmhiczBaTUtpblE2
            N1BVZDNJbCtkTHZPZ0hxeS9wbERHdjZKbWprCkh6dllNTXBEN09EQ3JkdlpzWFdQ
            VkNEZThEb3laYWVkb3VXL3k2Tk0vWDQKLS0tIDlMSmVrMjZJbGUzRnBwUVJ5aExo
            dUx4UU1mWGFtQ3VUbkNhdlNwcVZIdXMKHDTW9VlXEJnb94uBBnEHd6EBPB3yqtue
            eH23OLlrap7WPAvUXddTE1S2f4YdPwal4FPk1CQT3NMtsaHJWuS8DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T15:22:46Z"
    mac: ENC[AES256_GCM,data:DnTQbTe9t5AuXjhsDGz4AWK4vFyhAkkpvn4n0tmMPogp8/uy7QgiKKqYxF1zvw3GW2kNSnvJkbZBRemsCsRGYcY+FAtgFNQ3na7MyOCTMJbKlHycAARKhhkgbXjg2EMnnBMMgzbsLjnOKhx6fBN0LsztrNzR8UCy65y2aDmxavM=,iv:fqH+4LF3qm8UKxSepuPe8nZM4LBC3eFvap1IrIlNyNc=,tag:d/hIGFCX+MoBcCU90+huFA==,type:str]
    version: 3.13.2
