apiVersion: v1
kind: Secret
metadata:
    name: astra-secret
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:aNjzXdrl9UZYc+npaVXcHJuwIt5K6iewWR2aduCgcfdk3p8wdXwxSD5XLdtYTVXQAfk0Zx8=,iv:47EuQeIKBjzMLoJPCZblrcoRM8KPDlyJ+v+2u+0iHXw=,tag:ywokT58T5ScHG+Ov2CXObA==,type:str]
    DB_USER: ENC[AES256_GCM,data:rrli,iv:WQsmsNfYD2A4D3hACQl+b/2AvDxYkFVBRa0oOIfapYw=,tag:X/jwu2oqsnWKrUfnaHAlLA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:lhDZ9gwvvQ==,iv:r0ndjvZETtXmhzn/oToNEdZ74ibOK6nnnIjNDbnpFyM=,tag:2WnDOcq9pNFLIrBcyrkHrA==,type:str]
    STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:cXlJjjb/aHQzRRxLOL0dHIf70dQcRTNzWSp9uTiFbxk=,iv:xdUxoqXR9SixqYgUIKh58XfuOO1w72YyFsCHphTJ5c4=,tag:O8DxQ8DCSw2mIIZ9qKUIbQ==,type:str]
    STORAGE_SECRET_KEY: ENC[AES256_GCM,data:AVkxDDd/Pj/Hw7hq2DbZSF+d69EqU/BRmDIrH4ycawSWCOeWlzWJlTK5Soo/mgnfnkhZLdBilxBcy6EL/QqU3w==,iv:i8ksKp3wWClBwDxDVKcGwB5xgimaV3ipQdzy95F0wDM=,tag:Oy5nJHB/jaQ542f1e45vgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOTZwWS9ORkFsbDlaSEEw
            U1l3a3NTS3RnL043R1dxcUdEUHlYZHluaW5VCkdNYU51YXVTQUlwUTdDczcxMURM
            bmtoYW05bkx3MTJLZHBWYUJMWUtPeWsKLS0tIFMrUVpmd3NmWlNXZVdDNEJXaThh
            MzBwdXpGVGNrZnN4YjdDZEJVbENrSDgKUxAZwV4UQ+Xqf2Md481NJlNr1uKJw6Kr
            SD6unbd7QjjT9rd4ywGTOHR1Wf9vDqjocBI6eoKP2K04imAaIjHZyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T22:25:34Z"
    mac: ENC[AES256_GCM,data:6yTX1gLB68Dg0YwnemMMjwOBPQqRYUCVXsXsLhxJZgBidL3C+DUkCpmA8vibUq4JTztqi8jAZMYkwb030MIRmKr8gdgxU3QoW+TQdsLZx4WtEVBhqYKUVEUF2Fiz7BG5y7Y97c8kjEv3SMMQe3CadFUkczDT9MVcY2djoZfhRlQ=,iv:ZfIZy/D/fneqNvr9620OUAwsFMknytaWeUdAIdDdJHA=,tag:uE8uYXwrQ0WACkbuG03RbA==,type:str]
    version: 3.13.2
