apiVersion: v1
kind: Secret
metadata:
    name: astra-secret
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:aNjzXdrl9UZYc+npaVXcHJuwIt5K6iewWR2aduCgcfdk3p8wdXwxSD5XLdtYTVXQAfk0Zx8=,iv:47EuQeIKBjzMLoJPCZblrcoRM8KPDlyJ+v+2u+0iHXw=,tag:ywokT58T5ScHG+Ov2CXObA==,type:str]
    DB_USER: ENC[AES256_GCM,data:rrli,iv:WQsmsNfYD2A4D3hACQl+b/2AvDxYkFVBRa0oOIfapYw=,tag:X/jwu2oqsnWKrUfnaHAlLA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:lhDZ9gwvvQ==,iv:r0ndjvZETtXmhzn/oToNEdZ74ibOK6nnnIjNDbnpFyM=,tag:2WnDOcq9pNFLIrBcyrkHrA==,type:str]
    STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:cXlJjjb/aHQzRRxLOL0dHIf70dQcRTNzWSp9uTiFbxk=,iv:xdUxoqXR9SixqYgUIKh58XfuOO1w72YyFsCHphTJ5c4=,tag:O8DxQ8DCSw2mIIZ9qKUIbQ==,type:str]
    STORAGE_SECRET_KEY: ENC[AES256_GCM,data:AVkxDDd/Pj/Hw7hq2DbZSF+d69EqU/BRmDIrH4ycawSWCOeWlzWJlTK5Soo/mgnfnkhZLdBilxBcy6EL/QqU3w==,iv:i8ksKp3wWClBwDxDVKcGwB5xgimaV3ipQdzy95F0wDM=,tag:Oy5nJHB/jaQ542f1e45vgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V2tFTUgwMExuVDRFbkhB
            dm1QOTIzaWVhWDJqZFBaaktVcTVHQ0tkRVU0CjFZeTRQK3BuUTBPN0xtZkN2S2w5
            bnR1bTdrd0hJc2ZyNGgvTjhOQXBQV1EKLS0tIG14VHBYbHNFQ0cwa1lPbEkwNEw2
            dmdVODljc2kxRVdOVHQ5dG1aOHR6cU0KGM2Ym2KksLKaAJkRP7C7USxjfQxZa/3h
            UPuklrUVRsfYXCRS8FCWZLWuHrSFvVXmayPP3aGqbzT8bwoVRUhdGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T22:25:34Z"
    mac: ENC[AES256_GCM,data:6yTX1gLB68Dg0YwnemMMjwOBPQqRYUCVXsXsLhxJZgBidL3C+DUkCpmA8vibUq4JTztqi8jAZMYkwb030MIRmKr8gdgxU3QoW+TQdsLZx4WtEVBhqYKUVEUF2Fiz7BG5y7Y97c8kjEv3SMMQe3CadFUkczDT9MVcY2djoZfhRlQ=,iv:ZfIZy/D/fneqNvr9620OUAwsFMknytaWeUdAIdDdJHA=,tag:uE8uYXwrQ0WACkbuG03RbA==,type:str]
    version: 3.13.2
