apiVersion: v1
kind: Secret
metadata:
    name: blueprint-calendar-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:MqWD/LfRZ+R9jBU1eThL08KAJmY5WCEnHwDQ7dSjvG9lpIUFefpjAHLnzGuOoKtps/luOXspbRmCPo6T3K3QCv0HLLB4GlNaF0wTj+1iB099Kh0vew==,iv:m720TTGlUx+bfMfVzciwxWaI5XQci2l03yXjjRfeTSw=,tag:DKao0lmi3nXJm+7QMbQBTw==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:n2kCLZ1X+69l5I3+ij3zR3hQANaOH5QojvLL6HkuOalZqL2Dn5LGrzuJRsR00GFVyKt9fCqkgbAecYI/qusPgA==,iv:5yF7YUYmKPK5N+JHokxy32OR0DGsKm3cYKlJm327+ZU=,tag:2JHMNOuOYckuRQU0BdWO7A==,type:str]
    AUTH_INTERNAL_TOKEN: ENC[AES256_GCM,data:odobFDHbP9KqRPSGxRKpJppDlQnNtnPDJm1rMqzVdcskoqMIzrL12KvNig==,iv:8nvYJMrTNMXHj/0cYTvjdxJbiDgyoZ5Bv6Jwf+vLkkQ=,tag:/vzJPR+/ETQ0bpfjTBCEnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbkxLSzBocHJlamVFM3NW
            SEpMQ0QzbzhoRWVQbUsxdFRYTHhKd1RjUWlJCnh1bGVtWjY4dkZrcXVWejZFYkVF
            OUppQzJFaThDWXpwV2x4TG9CWCtRK2MKLS0tIGdQRzF3dFlBUGwzT1VWNTlFWEsv
            Vi9DcWQwZ1M1cjIwZnBacVNBb1RKNTQKu1XTDpDU+VizhpMRuQIGYQl1rGi3GHun
            cW4QxB9n2TCpEMaf3F98++0Q88PH1xOSMJmFLdPzlm/C9ToMiB0CZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T18:35:02Z"
    mac: ENC[AES256_GCM,data:PAneUYuXw+IDIBOTvjHKDHzLcGoH/b49HPp8jE9C2q2TGwdveIMwcIGrXLqt9Kodu/dsgFlGlZlgbemGk2WddT1m4gh2H+YJ8mo4+4YT9Cc2mEZt0DDISOqgheP5WF0ht8p4IqhLwIqxv8D34UCo6tW7m++EV1ez3LMLQA1C/TE=,iv:6DgrC3Fk86KmFAe4A2TmKOE1SXYX9vekuthC4ynn9IM=,tag:8//OoX122yIj9CsQIPLJrA==,type:str]
    version: 3.13.2
