apiVersion: v1
kind: Secret
metadata:
    name: blueprint-calendar-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:14cWKq7Aa+zz77hvOFGJGsHNCQBdzKXyAbPrKlPNrN96qlr5BGgfcBZYA0jhNGM5yBI6dl1q6TjweFHrTBxMaoBt/NrFzR2yV/q9vLymTV13A2l4WA==,iv:s1v+CMzT2PHpierWmAwHWHqZaX7yPJvL/edHOcrbqEk=,tag:PFPJ2oWJ2JorXd3W1hdVaQ==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:fJs14UpDKjJUIxoCYASk+v6qqC4WQpB3heMP9B97,iv:/zC84celA9MUZjWYKGswouwuvXBPbRkLAC5B/05bKvs=,tag:n9pjMZNNlpVuJe6VgQ5CNQ==,type:str]
    AUTH_INTERNAL_TOKEN: ENC[AES256_GCM,data:Qky4jJNu2wroQx3Y5vWxLKnUrKdNfnG8ZLIt7UU2h7NWH8mY84MioXvkQg==,iv:J8n9m+jWayH0Yx2exzPgZzLy2cXTOQ9w49LaVSVngxs=,tag:5rNwf6z9L8u/o368v3Vh7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMG54eWl5WlRtMHhCVFN1
            bmtySFFUL2FEeTJBYTJKaC9XejNpYTNtSUdRClp1QlVxcVd0bXRpUjZubWFBaXdu
            WENSTnFuRkxTUVY2Mnpxa2wvUDZSSEkKLS0tIGdXUC9IQnJvZkFOc3E2cFlGdW1t
            VHFYM1NBNFBkN0wyZkVWTC9WOW5IV1UKcoyjDnH8msFLWiCLA1EaK0Y2c+LC2vj5
            WxhouAu8jEfBu6DIi85fylm8PluFF7HGH4dV/3hSF0mb2f7dc0ZUFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T12:30:43Z"
    mac: ENC[AES256_GCM,data:qG3IZiT91xG0NYmTMggu26G6H2VcewM9hQ2EI++h2XfgbtRIb2dzLjOGQnBX3sOVYpTj7Koqlb/HXgZ6Sum1Ny9o2L7d4y/TT8A3izPpy9IV0eco1X8XibRJzqrOcl2iqcHHzS/5o/YuCE1Vsvmub0ocgJ4U85gVOvHY0HiD1gs=,iv:OoKoSYEdFECamVmBfso+Rby90hYg5zpGQAz/9fpdb1A=,tag:7FAzvs7Ge0BDuHOmL0F6qA==,type:str]
    version: 3.13.2
