apiVersion: v1
kind: Secret
metadata:
    name: blueprint-calendar-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:11YyeWWaYJC9YWiJ/2MhW+MqYBOZQwAP4Iu57PmCpRBKonwPKZHexv55yj4mxwDVq8ylkPSdp41q0gz1nNtrD24bLYnKwjfHbHStmzETL64s4LDiLQ==,iv:T+IqbN7+2gpyphDiS2/cpi0kUDFGn3vF14Zc0/pwte0=,tag:B7Nnmh+PakxDmexK8ak4Pw==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:hkLJYGH5GTB2O77zlUI2quXFgtKBeQJCQ98SkRxg,iv:RdEFRpimJejey/ehTGLe1SjiHSIzhWxcc4epZXSTcU4=,tag:gKBTAnCZ2ol6fz6NdD3R1Q==,type:str]
    AUTH_INTERNAL_TOKEN: ENC[AES256_GCM,data:MbqXgzQFz69ZcyU41/Cav0Yajf+lmu5uKeF6ZCYxIJJk4x6x+zZFKnU6rw==,iv:eXoe9V4TIIKNjaNnADoHeMyZ8S25+nJamdd5aJfUmJU=,tag:5j5aZg/ZEtJBYY5wesi9ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dUxyMHQ5TWIzZFp1VDlQ
            QjVWdGdUTmtRTGtxbE13ZVdydkZEbklMeEF3CmExWkx1STNwZGxRNmF1QVk3N1hs
            SzZFT2RCQ3ZJZUYwU0FhZ0tWQnA4S0EKLS0tIHVMRVRqcFZUMWFINzFVVFczeW1E
            bGppSk1GOHV0c2tyWGhIZmY2d20zbjQKRSv7ESjX96J/NRCkHeUHpHjVrZw1a4L5
            7ot2ropuUEs9U1L0eQcRtXvRe+v4vYnPf03CtWkYOZpTa0xgZdf2Sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T11:21:57Z"
    mac: ENC[AES256_GCM,data:Nb+dBSU6H7hNm6GILcu4HMsrWmi0SG0fPUrsfghY5hQEm0H0W7UjTn0BqP/Gt0LGl5KBbKbTGpk9bRLQkaisRmuzUDIJ420BuIwnCd5zZE31GWfyMKaVSr/PdxovWXJxijgWgsZlj38+zdIlqCwpkP75I2U5fdG1gmqBJStl8v0=,iv:/xGIVD4r5V6ELuOAOscu9vjnvsSt4Q4cY3rZWnqjYFo=,tag:OIWLnUCy1VM4dRiRWniAeQ==,type:str]
    version: 3.13.2
