apiVersion: v1
kind: Secret
metadata:
    name: blueprint-calendar-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:wkuPwt4HQ3XDGs0ObvPwPxnhMQ+FR7tsM1tWH9qFMpmJHmN8XQNchTgb9Q18bNvBCKoGFNJvIiXCs2VUtFidHZvnH0wKauK3N+kf+UjpBb66Hb2RPONg3ee28VfhiVkMUs9+U3q8AHYOPZfV7TK5DiKfFBCU9XjzULfp,iv:XuTG3dJRlqXQNcdwYLYoVejjZ9VeteZRbut2gLIb2Js=,tag:lpOIehvjIOCTW1XixCNfgA==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:+O/uBnSNm6zcIs9ClaAhUAluzd2gBzNdWpmNSGz+2Z8=,iv:4Gnv7at1JbmGxRGtJkUE3WlKB8NQFQJ3ovOz0xiUqY0=,tag:wpsnnd6p+mKmKawh5H2ZFw==,type:str]
    AUTH_INTERNAL_TOKEN: ENC[AES256_GCM,data:dQrZdYJqVOUcbYHzTapenkD5SBpGd2lkH+p2jf/wq9yXS38n+2rl2dUH0w==,iv:5kYr64CAjbLo8gYDnNkdVRutlYSzWe1Q0h52EqBpv+4=,tag:8xv3qYQFqSWL6sl7A7jQxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOEd6eVNkUjZST0lrZ2Vm
            UFFkbnB4QUpBK084OU9wdlJSaDlhMHN6aWo4Clk4LytmeGc5ZEtKZmwvVE1tQ3lF
            dkVxYU5hWWtaS2kwc1dmQVEzUDlaS00KLS0tIHFnTTRrRnRlRFUzeGY1TU9zYXp1
            QWpncGFsc0xka0lPYnVEeVhYTW1yd1UK4PAKhvfL3L71S+WYuJuTc191Ftc1W9Lc
            dp5VU4NlxPZ6GRYbEieuKfXfKAE5/1AToqiT0XHB5ZvSPWvmO+5nxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:15:20Z"
    mac: ENC[AES256_GCM,data:rq0p+P/rIRNxrUqWTqNWCXY6Rlwz9RwJIVgikoE/g8VTDBzUEBwTtHUn7BfFqbF520JyjqpdBmH7SkBDCJuX7h0SjdxNl094wklQycDEdt2HA50BnuD/uK4H02/dKBpWdogr/bGbyz6RM6/wratyVwuI1pJkmVBag6o/iadWvhc=,iv:pQeARZA3LvfwMOXUOF/N3biqAbFq/qKf+oMVFxFWcuQ=,tag:lfXBnaNHaMJmt8qm5URBMg==,type:str]
    version: 3.13.2
