apiVersion: v1
kind: Secret
metadata:
    name: blueprint-calendar-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:+D5BO8wUu+ZK6aGZUa6w15z1aUqeNGuFEZaKmjR+9ubSMSjPE29OuPtB0vnYPghKAKsqYaHYL38SuBztBRk0+DGH1886lxTOgESgfALRHB+EEHOSl7Z3y3az9OyBVMLjZWmLQLARZy6G9WImbELEIqTDPFCKwq3imORUyXVqOpA=,iv:1w8fR/QDhEjpIZ3CWX6bn3ppQch/J7eTGrfHAz2LAUw=,tag:Ay9aEQE1DAb4HB/B79I/YQ==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:JvJOlxHi8H7kKFOg+5Sug5rC5MVKwtjIsSVy+JzpISCLST4nkbGRdZkOEFWNm++rJ1+arIbkufyfrMiSVF+2dDHx,iv:wI6SAAms4z/iH2C2EwPZ5pkYgxVlbRlmQhXrOZ+mNf8=,tag:Ztytfy6BqzbAH6v82cZCGQ==,type:str]
    AUTH_INTERNAL_TOKEN: ENC[AES256_GCM,data:30GWf9pWmb7v/nRNK4SABDBobALB8ePGRc/WU/oJCT4ASHzapbD0ef+h/l1LRQmJuXmujrL7s4mA78gqq5YFuAEaLKg6,iv:3CIEPv9Yk8Z5KBOGGjpkRIXySlAw4BKNvsseIF/sQMI=,tag:KZATklQ42EHx1eNJdz3AYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RHBiV210RDRaZ2ltaTFk
            MXZyU0RjV3FkaENjeHhKMk4vRkdTanRpMEZ3ClVvVE5hWVV3QkZNL1NiYmlSY0pI
            Q016M25XbHQrc2tvYlR3eTZOT0NCWmcKLS0tIGNZTzNzZjJqcTNiMWNmWlNNazcv
            ZDFkSWlOR1hLNjlodVNFTTdnSlRPYzAKFQtfoprTTrnhmmRK2iORyqLIZyQK4l6D
            4CwC567oMXj0UQyig4NY1mhPd473Ap8pxCA+VZCM+Y7mE65p6KeO9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T10:50:30Z"
    mac: ENC[AES256_GCM,data:sixnZKGXPBOGiNEJhUatt7FLarcIeeM3Svs6LPFLOrqyg9epaClY7CGoblBOlAJeXFrkwCk2g9nD8yHbS8QpC1D9yeGRzhOU9LAt40i2XwFNH0x+pR5alncwCoiblPV1w2hEBUVvJ2lpfbXadhoTHdJ0udHcptIOFt6Gtg2GDys=,iv:RLTv4o6oS+/Qp8+HNld9tV6TE0nZKC4mM5+g4mHwMHc=,tag:MVqqbHv/PWI3Ft2swVXb0A==,type:str]
    version: 3.13.2
