apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guia-frontend
spec:
  ingressClassName: traefik
  rules:
    - host: guia.ionflux.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guia-frontend
                port:
                  number: 80
