apiVersion: v1
kind: Secret
metadata:
    name: guia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:2wV4yJJDN4H3M2qKcz4l9wNYOpTEhmwafG3R5PcYCnsJyAWtiB8tcjQOttoO91CCJv5K63SL+HqjlsDtPg==,iv:dTF7F1cRorwNn73yxUiumhZ51gOGsQhbp7hES132fYo=,tag:OLRNwYrpiVb6DnA5Ex5HYw==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:AiuUZyjrXWSEDe2g7cUpODdbd5SMbb+5WO0MldqML1s=,iv:hUlhr9qXDSB7yWS/TKZsLmeCCqnFdGbX5jFMCYhVD8E=,tag:UI0FDKcVXoYpGv7dDoot6Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:i8J71NwrMS6eLRItYnUk98SsSZb2Dzpdu/6m8m7V,iv:BGIFALg2Wlwp3qVST+luSf2+LkzN6G5hRyfEsnpuAWA=,tag:jSX8gnfebmgk/REJCd2WHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdjZ0cmFLaXk5dDY2THJh
            L1pIZ0QwdUx6ejBjSkl4dGtyaVcvU2d2TkdZCjdVNzJkUFRkYkRacUNHUjZnWk1W
            aGlzZStBWjZQOEg2dmg1MHVJYUU3WEEKLS0tIHQxR1NXZzdQTi9tUXRST3lsNmF0
            VzRldE0rd2hTbmVTUWJPWURnaGxvb1kKZMShoQMdwObofCQ9kZ7TE/zTnFuL+121
            X+ZQsWj/rDma3iXqaLXZ/mbrCX9lguTyx9/jb34aOchtYQ5eYlqLlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:31:30Z"
    mac: ENC[AES256_GCM,data:6zvxzt/E3doiSHoKL17of2mn+HOmmUSxVKPf5xANfzBZmSad0ufksKDv4vTbS4SCIOQ3ndm9Z8cOAeGAEhfR7m7K/k6oC4OELSNl26v0aHTw0uP9okACfbnlQl7tW7fFWrVToGZMEmgBoPloa0Rkk7ejSTeHW1FrDxXWDZtyEyk=,iv:ayE8lUnSvs3S6IvvDAT0jnu92Il0LzZA/FaggmI3ZTI=,tag:JG+YUqaJzOU69MsoD9q4qA==,type:str]
    version: 3.13.2
