apiVersion: v1
kind: Secret
metadata:
    name: guia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:x8Gn2hBpU4NUvnP96ClD6E1OS3beyHjuOa/4YmmKCAnheevkVBSA6BaWOp/HqqCB/8+LOzeTS7ctHbfPztQdLew08ynI3iyqfxpS9CLowtAHxAYiXez5tkg4LA4P/zfcfw==,iv:RsUNSUh4uv95CtydrxqwrzfaXQrZ8sFT/DBJREqEamI=,tag:OnKfhq9AuNZXlLbKQ6Gcjg==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:njvxFi59Dm0Usw0Cp+8D5aWgRMPQ3DJgrPC4s6LnjJg=,iv:XiGiOjZABIdeD1OpkSNt9OvtbvB8PVv/EA3v7ukRmdE=,tag:CeKwgNV5gptwUTQ1dgMfXg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ufAzFLcdu5C8ekV3OxQEMYzY2Pn8fzbU+cP/jwdF,iv:CJWJ5+w0tu7T4D+aZ1zm5xei/tWq3YmNUP9JT9afbqk=,tag:Vy+0tc5GYPqj4T7m5IZpcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdXVrSE9DY1FoRWticzJ4
            Y3FFcWd3RStVU1ZvUVp1d3dqNGVrbTRYekEwCjBnRUVQMlFYeCttYkx1YlhCVWFs
            V0NScjI4K3VlUXR3WHZnalg5WVdtM3MKLS0tIHI4ZXhDd2dORmNkR0djOGRyUG45
            R29FSkxzS0tkVS8xZmZqR1hCSDYxZlkK5SK9UAV/+K96a0gu5XWh4dONkp8x0hew
            AG2YI5MRKAkQVHXOODyS1QfkksEuusSLip9SgEsUuDWuO5gf7KVcBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:20Z"
    mac: ENC[AES256_GCM,data:kDyE2aDXnFMzWBuJnjDxftJlui79FAjeAT6TPUdXBD+RNURpvjACgcIntQkUcKgnu1BJWd1hITpJeK8VXEIbRPDLGZYnIcB+EoGrP3ItH8JYR8TYf4+9/rUR5/Q6ReHWfQ591UDbX7L5bfM2P557EDZ+RX+Jbm3WKHhJJPlVZGw=,iv:hb0saKcSakgoi9TID4f9DRkl7FFC97uS6SYADHTKIXM=,tag:EnCYM6uFZ+WGAmF/ngJz7A==,type:str]
    version: 3.13.2
