apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Global-lanz/gitops.git
  ref:
    branch: main
  secretRef:
    name: git-repo-secret
