apiVersion: v1
kind: Secret
metadata:
    name: norteia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:PPjcxjgdHziEv0rttdIRAkTKbxH5ZHn3rq8e3QYxbzjrKmdgKE1gijVKObg3dXiqT5VOa4M5OBO/C6qByVULog==,iv:82RG9vQNLorNv7o6Fr7mByLnGWvTLbZVpMxhgukrCvQ=,tag:wfp3EoFtJMElCD9aH3hdkg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:29Kt5RbkEzWBbEB6xe9hlBFIP6/4k3T154P+0s0+,iv:cxl6J2zJh7XRlpskA7pfB2znJ044s6F5r3HB30nF3v0=,tag:glWRpNip6GgOGgr9LPyeZw==,type:str]
    INITIAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:t+T1k6L7KqfL4Ke7uFqnv1ty9S8=,iv:DOPHYHZfSv/GVqJMHpZsKb/WdIULv6bJPa8q0r9KDVM=,tag:Htc2rNamAYzzeglrbdhqdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV2NKM2tZbjBYdGhCQzRL
            ZmdmT1Bxc0tacHVZeXcvTjZoY1NZR3hRa0Q4CmRNVkdiSFFqcFVXVXE5ejhZcDZt
            bDhBa2ZLZm13dGFQaU1hVWxaRkF4WDQKLS0tIDVYMC9BblVJMEh5eFEyQng5Um5p
            OHRicElscUs3NU1aeExxa2xLelR2Y3MKVLaZNJb0IUmytgPDX2V/mZWQJ6d88YDO
            gyAMd3xwjLhO2Pl9VwFIBK2MSuTGu+wDhFsZgQZVicBnP5wllZWEjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:38:03Z"
    mac: ENC[AES256_GCM,data:7cZurqv2TnbynKjXeoLTqByQATOso1ybFhPl8J+9IhcObeqWJX10hQPH0BLGRAZv9rfN6zX6qrMmu/LwAXlKRubdEiVUPxrEjPpqNZKfQMkE6ezP5JfS66l2u2v89V7kTRdZpQUHs0m8lwVex2CzRjKa/+Hv/OqppUmNj+0EMK8=,iv:6nv76j7+0lob4K3cN3LXr2o6Z+tzBwx9pP9RXmem/4E=,tag:J5g/bRWvf8FiKwSLCj1dvA==,type:str]
    version: 3.13.2
