apiVersion: v1
kind: Secret
metadata:
    name: norteia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:qxlLLcqzgH33tKfCXDYCdr6YhBEHKvZ4hi5bzmEDVZ6ADYewj/55UXkmCQMmO52F3/YOfAUp1TshxRqr7NtaZfNIyg99sgBvaEhZFUgBdd9WyubNEs3PCi610V+6NG+HSdd7cg==,iv:a359g5Vz+yCWxrwsznye1qj2wgBA079Cilylr/EJ7dY=,tag:qxFZYubg1yOAJRUt0jC/kw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:yB2eGbh5bP3Hrt1fB0NEV+FER0voRVhw0+SuHA7+,iv:Mo7ILUeq4nP47UzEVIZMhTQ3lvg6kd7qFWkM3qTJxXo=,tag:8Wwa6S5OYb7ILWa0698z7Q==,type:str]
    INITIAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:VkLVxgqF9eEh/9ol0yU3PBE3KVw=,iv:+vxjgfihVmxs4e6Pabe44z5fYuAJQ2rZpfZRq6zfkUY=,tag:Px+0F61sAIdB3en59z3opw==,type:str]
    EMBED_SHARED_SECRET: ENC[AES256_GCM,data:GRFqXYi27doO7/Ho+nwdbGv23ABiWBSE9JhZ7cBUDtg/DB8qfHu3hXMCfA==,iv:MadEsODfx9thK/mlX7UnpN9tobADwb5I+uGY7iQ9fV8=,tag:bGnwl9JPyp5D/aXU2CRR6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVVQ2WjhWOHYxTFk0TkFt
            Y01SZ1ZROWM0Ulc1WlRSbXFuTGFnMnhONUJNCmhJN3pnY3BxZDVHRURpZzM4MFNB
            b1ViVGhFVnhVaGNPeGVJUmVCR05jZnMKLS0tIG9TNDA2WUo0UUx5a3NIMEVPd1RI
            bzJmQnpldEROMkg3ZlNrc1d2SFZxTHMKOfsUhhMwMozkkhy64Aax1ZxPZCV+dzvM
            2BNnP0+mv5soOmKXjCvi/rIeazuQrxZwlAhgKMqMXvCi5jiyZuR8uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T15:56:17Z"
    mac: ENC[AES256_GCM,data:lvqtL80WXFJ4yIvDId8E62LhnpJ+bWkeELspxc08JuHPoaXXRkwrTIC3nwXC2ZnKedC/+1o6fBzOcwwp2ZGo/NFoKzFg+Gcff5pt+thKmeeJjH/BJf0Ny/fmZaFeX9WKVQCtHfJ5mAqgx5VP5diIGfIG6+jHLO3hmcXDFdnXL9k=,iv:AuIr25Qhblr/jg2QAHSm8oGP6G1jBLvGPjrEd8FCrrQ=,tag:ZxSjujtrRxM08qGFt42TyA==,type:str]
    version: 3.13.2
