apiVersion: v1
kind: Secret
metadata:
    name: norteia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:PPjcxjgdHziEv0rttdIRAkTKbxH5ZHn3rq8e3QYxbzjrKmdgKE1gijVKObg3dXiqT5VOa4M5OBO/C6qByVULog==,iv:82RG9vQNLorNv7o6Fr7mByLnGWvTLbZVpMxhgukrCvQ=,tag:wfp3EoFtJMElCD9aH3hdkg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:29Kt5RbkEzWBbEB6xe9hlBFIP6/4k3T154P+0s0+,iv:cxl6J2zJh7XRlpskA7pfB2znJ044s6F5r3HB30nF3v0=,tag:glWRpNip6GgOGgr9LPyeZw==,type:str]
    INITIAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:t+T1k6L7KqfL4Ke7uFqnv1ty9S8=,iv:DOPHYHZfSv/GVqJMHpZsKb/WdIULv6bJPa8q0r9KDVM=,tag:Htc2rNamAYzzeglrbdhqdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV1RXMXNwZDBWTktQSGM4
            MW53SkZvNEdtSUgydThvRWtaejh5N0tvTmdjClkxa283SmFRdllzOXJ6djRSZGRP
            VzEyYndCQlYwWStNem5jeU5Zajg4cXcKLS0tIGY0QmlQRmpUTTZRa2tvdWovRFQz
            YkdtcktIRkt1OTFMMXhRb0MxeGhQSVUKHNyyZoSCWpprrXUi5aQ5vHkyvB6d2fKH
            tSI2JTi3kBoJFs057WDZHvx+4NqAZRMVmVlKfh2FYu0JSS64V1Ylmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:38:03Z"
    mac: ENC[AES256_GCM,data:7cZurqv2TnbynKjXeoLTqByQATOso1ybFhPl8J+9IhcObeqWJX10hQPH0BLGRAZv9rfN6zX6qrMmu/LwAXlKRubdEiVUPxrEjPpqNZKfQMkE6ezP5JfS66l2u2v89V7kTRdZpQUHs0m8lwVex2CzRjKa/+Hv/OqppUmNj+0EMK8=,iv:6nv76j7+0lob4K3cN3LXr2o6Z+tzBwx9pP9RXmem/4E=,tag:J5g/bRWvf8FiKwSLCj1dvA==,type:str]
    version: 3.13.2
