apiVersion: v1
kind: Secret
metadata:
    name: blueprint-auth-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:E9nsoteDK9MfKoImtoSvLd2v0lb0PFM+jooxKcg/WHLRzEkwx5/751RUPsOw+IcBPXIQKGt8ENfZz3IpvsB2TBEOdaUU,iv:saLRCIckSrxWLoTFehWCMMsoWv59/jD93xPut/HRVcQ=,tag:jzs4BU9jwL4QbgGmIynEZw==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:DyeVrRFQDZH8+9ZTVA8rWYWRL3sxsVk5axefhOoqyk8=,iv:PWj5CzZvUshXBqS3soeWgSIt/6MCmyac4RxbDWBzKqc=,tag:myiRbUWCmWg+BqgTy/Yv9A==,type:str]
    WEBHOOK_SECRET_TOKEN: ENC[AES256_GCM,data:28zqiSRHpzAO28f624a6OaEDvPT1JD868NgvVg==,iv:Sv9Is7GdM09oqMZkdsEUK1CCD/m8bEV4iSjB/PToMT8=,tag:adAJJ07pRtboPXsSqp4DFw==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:itr+5fNZVkWi2zHbAZkhBNHx+sc=,iv:nexSzs0AYjHniwzlzfr1w6chaREvbwYoJjQH9iGKJlg=,tag:zqBPhv5k52LROa9fvt88Ng==,type:str]
    SMTP_USER: ""
    SMTP_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcVB6eWJicG9ibTljc0FG
            YTlnTjZRY21vbzZ5WWVCMklHeDRrcUREaGlFCkthTXdTalRkbVZWRHQrZkR3bkZF
            Ry9ZcG9lN00rU2tHRlJvVHg4Q1dFWjAKLS0tIEIzb05FNW9maVhVZjVWWUV2Mm9w
            TkRGckVvS29UcDU2T25MZXRSbHJkTXMKtWI7q+r4wUGAgv6AL8hGaTaABjzPBHOK
            QjoZaOIgM9rOMZ9pi3ED+J7DdTjpje+nhxJHWAM15Veu1Jux8RlnNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:33:26Z"
    mac: ENC[AES256_GCM,data:QHmdh42TgRF1Y6iV3n7bDaSl/00HH6bSb7ksQC8KXcpy9Sg50BbxUMQgxzOiGCrmHHTR8QXQs8rqSgk4+ZasWEtaRNbnzI03jON7gGVmDvaRmGsx8CSpBINhJo35Wy+BoCHwBEQ81uq19sMSSXs0J8ivsji83A6h75qJYnxY6Eg=,iv:y9hB9V/UGnv5JXM1e57A+Bek4Hv8Mgl5Ume/e48ZHac=,tag:XnjEQ6Higl5sc1XzLjLj/A==,type:str]
    version: 3.13.2
