apiVersion: v1
kind: Secret
metadata:
    name: blueprint-auth-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:QQvC3H7pUyOnwkeE6RoYZGZOy4YFO+ndp4BSLkI0qQn2OlxsE/yQW4AFZFYvTbw0ZtgAN0ks2TEElTvTV8XUM7nQqA0C,iv:wAFydEBwsloQF60R9ckGImHfgE1JNFZfDe8TNhzYT8o=,tag:ZVxXhGHfOdbeHXaPz19yzw==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:QmcSqX48iZ4Ax8TMjIJpseeXysPHFJOI0HzQ3v4sl5E=,iv:fZA5s72IU2f3xxcXdbGVtWW6fZ1PJ60xSArUHoxiKiE=,tag:EYHsGxGJgA9vGg7Tg2QfgQ==,type:str]
    WEBHOOK_SECRET_TOKEN: ENC[AES256_GCM,data:IW67DTKSp67bS6UtG8tN9bE8zLHH97OPSfS+qA==,iv:ST8kisqH4Nj9GeHnlMuLH94mLu58LkcDEU4XJECAoQE=,tag:RgeZCKhiSeCROk9Ru8tslw==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:gSf3HMAP1LefI3x+AJdZFKX2uYc=,iv:weXQ1xCv86PdY3UlYTWjZ2W9EoBQOcpz8Xz+/K4PxLI=,tag:EzsRChugh31C8emzxL0OMA==,type:str]
    SMTP_USER: ""
    SMTP_PASSWORD: ""
    INTERNAL_API_TOKEN: ENC[AES256_GCM,data:vNwTOqqTK1sRUkTx5uQI8zEH53zpi6658eYbMh/Biu/giAIHk9L8ER1gkg==,iv:bUi41/zo3E9iVR6JT5t2UcL9Z1HNBzwZ6/w7sB+vKnw=,tag:xHgm30ckqKTmQgPzjbPyOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SGJvTWVVNWF6d1pZMk00
            OGhnVm04cWd1ZVFZdVplQmJKcEVqbWpmb2pBCnFZbG5UcmZuSDZXUlN4eGxrRDRP
            Q2ZiVU9Tc01iV0QvNVp4K21Kd1ovSkUKLS0tIEhoMC93VTBkMm1GNi81WnZrcCtj
            K2lzQTZ5SmZ4M3Z0UzBweStrK0hITWMKp0e017PZkqwUmpYw9I86dx6XFbhW38nI
            E2GO7EGmGqDNegrbVxx7tOOsVZ7vWcTrrHveYRkcbIgl95ltu+HbCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:14:37Z"
    mac: ENC[AES256_GCM,data:Z0Xtq6OSNRb5ahge0ASHaw+oddK+Kc323Weg0tD20YWTvdgsXsm/ddS1q6j7E5K9jAHsAqXW3elzYoeKlYVBJ1oREytFWTdLdERZlT6B1+CXPCMFWu0IrbrOOZpyU50wdy4J7sV3Stng4N/fWwXY/s82gNbkCDGWNJXXLdeb/nE=,iv:dLjvg6DjFsgN7dyieB0gz8wnjffwqZFp7g7r/+XPtoc=,tag:nBrosTKx+6TSJAFQWhyVQg==,type:str]
    version: 3.13.2
