apiVersion: v1
kind: Secret
metadata:
    name: blueprint-auth-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:iUdly+spchoTDYM6pupvO9ItpeM5cROWVd7TMzSmNGviR/+Jk24tW2Gh3TwHP2bckRwc7OcKk0AE2Y1cXPr03wnCPR0P7dgY9PVS9vctt7jm5ak0DSk3Oo9s5QFoMzb2jvcTCaNjRdsr,iv:ZNF5QErXXYgRRUfNmEag2bAgx1tYCbPKq8iGIieGRuw=,tag:UAz35lGpCj2xJONOCAAJpg==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:WrpcGWkPNiqADdRwTUd89T6Wbkxfgd9pzbLYpcVTLe8=,iv:oWPauHJVKvBiEDMeEWNwAIvaJTL0/g2gC2IfsmroYlo=,tag:9inTzh5VlHt9XTCSxFkeeA==,type:str]
    WEBHOOK_SECRET_TOKEN: ENC[AES256_GCM,data:BsIupCiFUMXR04HBXsmjEyuegulZ08Berl8yoQ==,iv:Sd3JFtH774yo1XBb9oIthGrx6ERbdnFmgj4Etd7Vtwc=,tag:QwJIv55KhPi1kAGdMwHtkw==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:V+8VHobEYZBvqfaCRbBw3X+Qdh0=,iv:v/PToy/s6KGdK4ghwphcabo0NRuOTwVzyWW4EdRyDL0=,tag:b8FYnuwTFWm1rVfa6DXb1A==,type:str]
    SMTP_USER: ""
    SMTP_PASSWORD: ""
    INTERNAL_API_TOKEN: ENC[AES256_GCM,data:samxdxHH4MGFVn4AUZuVN3O7yigpCjexoXXwiMOOtD2+snjF5px4iAzPEw==,iv:FMWnJsQBVSeiQf9/JSVJMi0461P2pt0KxTLE1hxvi/U=,tag:H6F+IgCoSPTvw6eAMo+4NQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQUdQb2V5dy8xdGI5RnFV
            bXJ5d2RXSXFabWlzZkFvM3pZWVVhZktpSlNvClVrVXprdDlLNWxuV1BidjFTUU5H
            djZoS3J2TDdXM3ZPUlo2eFhSNUljOXcKLS0tIG5MVVNWRWFvRldZbE5mbjJoK0Zs
            RURMR1h5dXRITHhCQkIyTGxoRGUvSncKWfdhp7+8FVZcJ12KVD2wZgz7Vgkal/6C
            XUbkEkjzh7sFIrfsGvi8XeRk6cO0KDNgVvmy1F4aNb01JzHfUh4N4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:25Z"
    mac: ENC[AES256_GCM,data:1Rla0/KFzlpa6bV9P44LK6af36g2blViaWsxsks9bCP9VbL7OELBy0UwgyVN7IPt+NOhJyuxVGWS1T13jN1LmKc/2uBmsnO6MdxeNWyjKfqMNGoDGGMMC5YLkQsuwL8PjSCVSl79c1RnJpT3XoSpIh9rwMc4KqYpmLEF/k+pAUs=,iv:exjX/5fMlzOBZzH8gi/kFHUtovhErdG15OiPgRzSs3s=,tag:2MU0pfIlrvBhu5ITMosljw==,type:str]
    version: 3.13.2
