apiVersion: v1
kind: ConfigMap
metadata:
  name: guia-config
data:
  PORT: "3000"
  NODE_ENV: production
  APP_ENVIRONMENT: qa
  AUTH_MODE: external
  MODULE_KEY: chat
  AUTH_BASE_URL: http://blueprint-auth:3400
  AUTH_PORTAL_URL: http://auth.blueprint-qa.ionflux.cloud
  ALLOWED_ORIGINS: http://guia-qa.ionflux.cloud
  N8N_WEBHOOK_URL: https://n8n-qa.ionflux.cloud/webhook/guia
  API_BASE_URL: http://api.guia-qa.ionflux.cloud
  MODULE_KEY: guia