apiVersion: v1
kind: Secret
metadata:
    name: guia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:BeSEKDlE9b4IW90ewT3MjFeeu8QOzaUkjUc/oRxZinYQ/wqTaSxktBZb/z53idcCWXz66YltNaxQiaI=,iv:f4T6s7amVrHc2ajnmC9ZBV54Qz6tpU5Jo4dymaYPaxY=,tag:8rSXEdN2c8gj5ueAVPfMOA==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:Zhq+MYzOIjpxfT9izzyQ4GHkF7j5O/6n6pqu19cg,iv:gc6nw3VnuscMluaGRgapN4PeXGXn+Kjz2dt9mOAbHok=,tag:KXGtP7bzpqcfBIRsRQySiQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:KU4QEXyqCuuXxMopAIHtKYRHGFYZMYGGZBGJHg==,iv:0m4LcDA1K8uaYWSF3DL81BFx6yMGB2ilbUILf/wbzQc=,tag:x03Cae5OECskOFYUsl3UuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZjNoUmlaRGtVZWpwbjhp
            WGw3WkRTSDVIM3N6QjRITU9iTzNaeUZ3ZzBRClh5SGNFeXJtTmkzVWU2VFhZVnBl
            bG5BaWIvK1lYVjM2RXpWN0ZwR2puV2sKLS0tIE5meVAvTitsWVBXZXF3bXo3VEZV
            WVo3SEZjNXRjYkdmbWhEb044NFRyTzAK75p40usB3dHP/jTlnYn5lzRgxpLwn7Ai
            yngvXlFukosolPV9cjC0bVDj0NaIJk/w4U4FXoswEHoMVE4/YCpuWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:31:30Z"
    mac: ENC[AES256_GCM,data:xG5foHHtQXamALRpE3gqGMeyBE5mzc0iiREv9PKCVlragZ2oyjOVmMYX3RQudJ5MzcNz5udYILzoDgmEv72rQ8dAGmg+IZ4xCUlmjzcwOl6IVQKwf28D4H1tjtpOA4Uw9TgCZ55nrGY9GZSImVZJe+5KgHZ0HVJ9Id+2+gd6RIg=,iv:8uZxsyKmuTRERFay+F6tCPLwWbw3BSx85VB641WWPqg=,tag:xBLQOhGHh+7iusXNuzPWtA==,type:str]
    version: 3.13.2
