apiVersion: v1
kind: Secret
metadata:
    name: guia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:BeSEKDlE9b4IW90ewT3MjFeeu8QOzaUkjUc/oRxZinYQ/wqTaSxktBZb/z53idcCWXz66YltNaxQiaI=,iv:f4T6s7amVrHc2ajnmC9ZBV54Qz6tpU5Jo4dymaYPaxY=,tag:8rSXEdN2c8gj5ueAVPfMOA==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:Zhq+MYzOIjpxfT9izzyQ4GHkF7j5O/6n6pqu19cg,iv:gc6nw3VnuscMluaGRgapN4PeXGXn+Kjz2dt9mOAbHok=,tag:KXGtP7bzpqcfBIRsRQySiQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:KU4QEXyqCuuXxMopAIHtKYRHGFYZMYGGZBGJHg==,iv:0m4LcDA1K8uaYWSF3DL81BFx6yMGB2ilbUILf/wbzQc=,tag:x03Cae5OECskOFYUsl3UuA==,type:str]
    EMBED_SHARED_SECRET: ENC[AES256_GCM,data:whjxvdVNh2YLgYMGyc+aMZt0XeLJd1cVxYKoTxq4GGm6N3Q5fcicS45MY0xrrFABnUsxQD7XzGzqzaRVFJF62Q==,iv:3yZB266x2zXTXt7v5khZwkc3LCJ1wC5LYmGQEhpuwAQ=,tag:eO5o3AbOazYtROcWaQcSZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZjNoUmlaRGtVZWpwbjhp
            WGw3WkRTSDVIM3N6QjRITU9iTzNaeUZ3ZzBRClh5SGNFeXJtTmkzVWU2VFhZVnBl
            bG5BaWIvK1lYVjM2RXpWN0ZwR2puV2sKLS0tIE5meVAvTitsWVBXZXF3bXo3VEZV
            WVo3SEZjNXRjYkdmbWhEb044NFRyTzAK75p40usB3dHP/jTlnYn5lzRgxpLwn7Ai
            yngvXlFukosolPV9cjC0bVDj0NaIJk/w4U4FXoswEHoMVE4/YCpuWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T14:52:17Z"
    mac: ENC[AES256_GCM,data:+GHxowFq6EbnCJhKF8VPRL1xuk+8CFgT6A138Wq3HqdpqBuv2UfWdE7MNAmaIhVSZjQIIK0zKxvHAhjJmLRliLW3QRM7YBVtv5Nz1gLdVUPW1Rm4HaSjWOeQF2TLRkaPYYXZWBdvpBZ04gfj04ZwrcAEJsS1BEdytZXRhfmgNC4=,iv:T6eqUg60SwRSEKPZ1j9pKVxPlIG8S8kH6w/cAfBy31U=,tag:E5d8+n9p1ywLThqV82c7ew==,type:str]
    version: 3.13.2
