apiVersion: v1
kind: Secret
metadata:
    name: guia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ea8sZcSrJajF9K0qTT3+nISkI7V1LbNR3frzlHWxGHKf98Igay26mHXtsFVTxegsJ/db9204qZQfkmI=,iv:y/0avDAtdNOXmVAP3oUNxkIEDHwgESD7y1a4ogSmXEM=,tag:n0l4C8EBVW1RzDV0bXx3uQ==,type:str]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:xZZ2YkLGbLa841TX2C+yHtFLd7N1z7gMKfhCo3YJbrBDWiPzEyfxWUDuwus+woMM7LJWEg4OF3wlME7gBg0l+Q==,iv:YnE2mqpNRZt2Z34LyzDloVx4O7dQ9Bkx3BRYKLS71CI=,tag:IYBSgLyi3Ag+jiI+6VD/ZQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:YPhwsFvH5oOTKnzl5TrSoEgPoY5aSCvqh1E5z4QU41ZHjK/MD1vMaBJMPVUS77NXhmfcL7Z3/DtFzuLW+JVCNQ==,iv:IDd5vOcV/fD5b9gsRDVC+Oar5jXiNWxGf71YNGCNmW0=,tag:FDE5NxOHnxifaFSqDz5BNQ==,type:str]
    EMBED_SHARED_SECRET: ENC[AES256_GCM,data:dIbNERxpIRi6qnJXMGBiNASKcSTQ7NUecNJneZDqXaXFoC7DiZ7ZfDmC2rowLM+Fq4gOsRVzSzv6IN+PJypOJg==,iv:EXr1BtgQnguFRGEtVrfzBkt+Omkw2/GEoJ2j109JsBk=,tag:P8AqNoV/GGCD1CxDuktxYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWjU4Z1NETG9WLzdsTWFQ
            NmVFdXFzaENPRjRWbFVWVm1CZGZFc0l3NEhvCjJrUEgvSjJINWpLN2thUkRMV3VZ
            TTJjUzlKU1VJWnNxTTZrVzZXcWVaRUEKLS0tIGNTdmp5VU5oVjJQMHJ2NlNWVVdj
            VmVhRzNNRXptUEtGYjY1OEVjd05BdGsKKaPsPCxUqXLJlgqGVY4nSqWG2N5BTUFR
            aF5ah7MeAdaiMeu1A9LgW7rS8YbSMYWgOm/IqxlqTKGxGkFKX/tNdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wtz65skfru6g47f6ygwtqfkczfn3h8wtz0kxwzv2r5saud8jyvuq085z05
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T18:35:03Z"
    mac: ENC[AES256_GCM,data:a0KgRBrJP1Xm8ggru7cX3B+3/SjxBrfukhic+pCB0lKV6cM0GyV4fj4xyo9P+viEEVwjd+6VFNiXYpnYhdcjEEWEk8YVu4/Tfgsr3eDD9Er7g5kixN7JUJtJ67D8pPaUnAeIIl2dP+W9GlUgJ3IQNkuV2H9iT5AbtxyCTQfDA0E=,iv:QABsiVt0xKLkjQbp3JHz1As2gK8h8dOTCmn5oxXg9e8=,tag:CLNPUdYoBvksuwQH1gfdpw==,type:str]
    version: 3.13.2
