apiVersion: v1
kind: Secret
metadata:
    name: guia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:WYxF23Wsgtk9qxk5B260MZDkBwdxee+NmcYu6C/ZQJCLUeM9pAf6M/h2BKuk6UAbrDVeqYLt5ELTnbI6,iv:mO1Zt6/dD/qrCkF9IP8S9KmzgSBhXuonRXgJxl72Pak=,tag:/BHFum74mcMZRlD3jszLyQ==,type:str]
    #ENC[AES256_GCM,data:KeFKuVmvtqg7nOYzC22yehex66wjkdqlTx38DC0SQC9RPm0Wkx/wAmqG/T1LY5l6KnAhpIkMRcTQi1sH4ENCb9wqKCqbdYhFpA==,iv:YlGlj+WE8i07Bu3d4t2uk4cvYDzJHGf0C3Wbna1xM5Y=,tag:f/ARrUQ7FebiypmBbRiraQ==,type:comment]
    AUTH_JWT_SECRET: ENC[AES256_GCM,data:xXwu0SQergA6XndUWBP4ssRaQb4CEmzctrUmx+6FvduZZxc67U83S4Lnne8F7BEeHuDtsyCpz6zUB1ged1+vXp92oK9Vm+0EC1zCNLtd2tU6yjhnRi/ToJQ4euy8lz2Fy4HmgsxN7lj+T+MsT1+/kCM3NK1xiV77nbaw42Vpm/Rk65ACJpER0IbZQIsvXy6OKGS9al/7fYXnqegb5s3xecvlUJADeWsqosKfNg==,iv:6kBBuATDuWV7fNRW7S0S3Ihn6UNv86d6tet0GZIKhKo=,tag:eBdcEMumzfYC96k7xuRk8Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ffTj+Qk05ZqK9Fh106rCZEdTCYXRfcbQ5twi5Wc=,iv:n+3nbF8dcrRdkl3fockzznYIKkX4R81l+FBznn5OETY=,tag:aqTcZI2eCejqzDEMU+nkSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOHVVcG9JdVJwZ09yQmpj
            Y2I0dEFCUFVSUHA1VTVQR2x1V2xySjFCWXhrCks4YzVZOEVUN3EwTkZ6U1VLZ285
            Z3FjTCtleWIxelpIdmpjUm9NL2RYUncKLS0tIFJXeXZBcEUyNkY2UDg4MFhlOVY3
            ajRlcWFqS3Z1Y3dQWTdCNmNsRjFtakEKdkyE0s43tYxbameuCT7flxJX4am5JT0K
            ThtLCOEHRjuMZSDTScu8hXC2SELSTHMvF3E4X5SkRibBt5wlxXo5qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:31:30Z"
    mac: ENC[AES256_GCM,data:PIsd46IIGrpYbpl0aWWuug1Z8CMKio1+bpQ+eLsi3IuVzsj060twx/TLtUHoC3Zwjw5KJYjo8ZtHsBRRkNwF1+BUWK6NUieTb6ifot8+p75AbCvDr2nDtFZSTq9ZXdQr2CuuGYlflnd2IRifJOJp5CXfxmD6OMNMpOSoWakFFVw=,iv:2Qw9z/gKyFR10JZefc/vBB/iQUiahXFOEv0ea0ORzmM=,tag:tLUCrM8Hdxoi1rUbnzT3QA==,type:str]
    version: 3.13.2
