apiVersion: v1
kind: Secret
metadata:
    name: norteia-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:fBnUwpm07nVfbgJu8ntkVN+7udsU2U1TY+L+csVfHn2auCQY9x/kcyUp34I1cTgsR2ik82DJyQ1R6BVYMbY=,iv:zZcJuwK+GzgSDz0SJ7oVVplLoFVI1eq892OOVq0ArOA=,tag:HvgfOfC6kLzJe6lh5ZCE6g==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:R63a/z226adTvLQ6fPZSi+WL6k9NzpBbQsqT7A==,iv:pvk+pAuc9/bOD9h9RubY2zLJ8duGAwmF+zbCYewzjUI=,tag:XiaRZd3om/49FfHKlC+sDg==,type:str]
    INITIAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:MYnbJG+JgjU=,iv:kBma9rqKS6eVJ/ih+1fgxsBKcwREC0pM6l3u/mRK7Oo=,tag:qhlNwvMYN31hScnEK4bjAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYnVFQlQyMFAxVWJmeTFR
            d0I4VHo4VDdlZk1mTk90Z2RyYmt3YjFieWxBCjUyeVFFNGUyVDVxbkxVNlpVQjVJ
            aEg0Uk9NQXhIRmwxelQ0cGM1ckxSODAKLS0tIHVGallNMU5VcmZHWlAzd3dqU0ph
            NjRWSmxZd2lMUWk1ekc5akJtSmdXclkKSatcE/w4wt8SwmQog9YTegIOJrBk8vzG
            xZMovXKqFGKRH+G+2yxCyZ9uT8FgK1tU9zMbaMvg8cyI+dB/KgNR9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16l29n9xvgd3ntzl70lkrfgfnkjx84u048qqewmesw00h98ucwpyqskgxq6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:38:02Z"
    mac: ENC[AES256_GCM,data:8YZbIe5ugz6+WxQ/35UIkz0XVXM68vAETXhH5Da213g/EOMG4IviXq8hn1zcek6p71ko28Fw5SgsPL5bYEAA5x6SryVuK+7CbEVzSyoMMv3jqpg9M67USn3nBv0KBD6Xlqm9ZxtdgNHN5MYETOjHJOf91kxhWjUyMxw8PigQYRo=,iv:ianssRebdfi6z0cZUCtezWz2Uv4G69Au63Y9q1YE0mc=,tag:TBU2ncMW1mcBCp3H0VnwLw==,type:str]
    version: 3.13.2
